#!/bin/bash

# Explain basic usage
function usage {
	printf "\nHOW TO USE
create-vhost [name] [path]\n
Example:
create-vhost \"myProject\" \"my-project/public\"\n
If no path is specified the name will be used as the path\n\n"
}

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# Check if name is specified
if [ -z "$1" ]; then
	usage
	exit 1
fi

# Set variables
name=$1
path=$name
base_path="/srv/www/htdocs/bart/"

# Check if path variable is set
if [ -n "$2" ]; then
	path=$2
fi

file="$name.dev.conf"

# Copy template vhost
cp /etc/apache2/vhosts.d/vhost.template "/etc/apache2/vhosts.d/$file"

# Update vhost file
sed -i "s|*:80|$name.dev|g"												"/etc/apache2/vhosts.d/$file"
sed -i "s|ServerName dummy-host.example.com|ServerName $name.dev|g"		"/etc/apache2/vhosts.d/$file"
sed -i "s|/srv/www/vhosts/dummy-host.example.com|$base_path$path|g"		"/etc/apache2/vhosts.d/$file"
sed -i "s|AllowOverride None|AllowOverride All|g"						"/etc/apache2/vhosts.d/$file"

# Restart apache
systemctl restart apache2

# Add entry to hosts file
echo "127.0.0.1 $name.dev" >> /etc/hosts

# Commit file to git
cd /etc/apache2/vhosts.d
git add $file
git commit -m "Create vhost for $name"
git push

echo "Created vhost-file, added entry to hosts file and pushed to repository!"
