# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1453914191);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1453914311);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453913715);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1453913956);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1453913835);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1453914431);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.appRepURL", "https://sb-ssl.google.com/safebrowsing/clientreport/download?key=%GOOGLE_API_KEY%");
user_pref("browser.search.countryCode", "NL");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "2015122500");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1453914072");
user_pref("browser.slowStartup.averageTime", 2165);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "2015122500");
user_pref("browser.startup.homepage_override.mstone", "43.0.3");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1453999995432");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1453913657333");
user_pref("datareporting.policy.firstRunTime", "1453913595431");
user_pref("datareporting.sessions.current.activeTicks", 69);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2135);
user_pref("datareporting.sessions.current.main", 50);
user_pref("datareporting.sessions.current.sessionRestored", 1745);
user_pref("datareporting.sessions.current.startTime", "1453914070463");
user_pref("datareporting.sessions.current.totalTime", 548);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1453913594617,\"a\":47,\"t\":454,\"c\":true,\"m\":280,\"fp\":2427,\"sr\":2655}");
user_pref("distribution.openSUSE.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1453914192);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "43.0.3");
user_pref("extensions.lastPlatformVersion", "43.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.3\",\"st\":1453909973000,\"mt\":1451583197000}}}");
user_pref("gecko.buildID", "2015122500");
user_pref("gecko.mstone", "43.0.3");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453913658);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "2015122500");
user_pref("media.gmp-manager.lastCheck", 1453913658);
user_pref("media.youtube-ua.override.to", "43");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1453914070);
user_pref("toolkit.telemetry.cachedClientID", "7cfc33ac-ed52-4ab9-be3e-fb17ed3c1e36");
user_pref("toolkit.telemetry.previousBuildID", "2015122500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
