"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,da,ba,fa,ga,ha,ia,ja,ka,la,ma;aa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this;_.ca=function(){aa.Symbol||(aa.Symbol=ba);_.ca=function(){}};da=0;ba=function(a){return"jscomp_symbol_"+a+da++};_.ea=function(){_.ca();aa.Symbol.iterator||(aa.Symbol.iterator=aa.Symbol("iterator"));_.ea=function(){}};
fa=function(a,b){_.ea();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};_.ca();_.ea();_.ca();_.ea();d[window.Symbol.iterator]=function(){return d};return d};ga=function(a,b){!Array.prototype[a]&&Object.defineProperties&&Object.defineProperty&&Object.defineProperty(Array.prototype,a,{configurable:!0,enumerable:!1,writable:!0,value:b})};
ha=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};ia=function(a){var b=ha(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};
ja=function(a){var b=ha(this,null,"codePointAt"),c=b.length;a=Number(a)||0;if(0<=a&&a<c){a|=0;var d=b.charCodeAt(a);if(55296>d||56319<d||a+1===c)return d;a=b.charCodeAt(a+1);return 56320>a||57343<a?d:1024*(d-55296)+a+9216}};ka=function(a,b){return-1!==ha(this,a,"includes").indexOf(a,b||0)};la=function(a,b){var c=ha(this,a,"startsWith");a+="";for(var d=c.length,e=a.length,f=Math.max(0,Math.min(b|0,c.length)),h=0;h<e&&f<d;)if(c[f++]!=a[h++])return!1;return h>=e};
ma=function(a,b){var c=ha(this,a,"endsWith");a+="";void 0===b&&(b=c.length);for(var d=Math.max(0,Math.min(b|0,c.length)),e=a.length;0<e&&0<d;)if(c[--d]!=a[--e])return!1;return 0>=e};String.prototype.endsWith||(String.prototype.endsWith=ma);String.prototype.startsWith||(String.prototype.startsWith=la);String.prototype.includes||(String.prototype.includes=ka);String.prototype.codePointAt||(String.prototype.codePointAt=ja);String.prototype.repeat||(String.prototype.repeat=ia);
ga("values",function(){return fa(this,function(a,b){return b})});ga("keys",function(){return fa(this,function(a){return a})});ga("entries",function(){return fa(this,function(a,b){return[a,b]})});_.na=_.na||{};_.l=this;_.oa="closure_uid_"+(1E9*Math.random()>>>0);_.pa=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var qa,ra;_.m=function(a){return void 0!==a};qa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ra=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.sa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ac=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};
_.ta=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ua=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:qa;return _.r.apply(null,arguments)};
_.va=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.wa=function(a){return"function"==_.sa(a)};_.xa=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.ya=function(a){var b=_.sa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.za=function(a){return"array"==_.sa(a)};_.Aa=function(){};_.Ba=function(a){a=a.split(".");for(var b=_.l,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}; _.Ca=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Ca);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.Ca,Error);_.Ca.prototype.name="CustomError";
var Da;var Ha,Ja,Ka,La,Ma,Na,Oa,Ia,Qa,Ta;_.Ea=function(a,b){return 0==a.lastIndexOf(b,0)};_.Fa=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ga=function(a){return/^[\s\xa0]*$/.test(a)};Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Pa=function(a){if(!Ia.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ja,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ka,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(La,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ma,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Na,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Oa,"&#0;"));return a};Ja=/&/g;Ka=/</g;La=/>/g;Ma=/"/g;Na=/'/g;Oa=/\x00/g;Ia=/[\x00&<>"']/;Qa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ra=function(a){return null==a?"":String(a)};_.Sa=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.pa)()).toString(36)};
_.Ua=function(a,b){for(var c=0,d=Ha(String(a)).split("."),e=Ha(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"",q=RegExp("(\\d*)(\\D*)","g"),v=RegExp("(\\d*)(\\D*)","g");do{var O=q.exec(k)||["","",""],P=v.exec(n)||["","",""];if(0==O[0].length&&0==P[0].length)break;c=Ta(0==O[1].length?0:(0,window.parseInt)(O[1],10),0==P[1].length?0:(0,window.parseInt)(P[1],10))||Ta(0==O[2].length,0==P[2].length)||Ta(O[2],P[2])}while(0==c)}return c}; Ta=function(a,b){return a<b?-1:a>b?1:0};
var Va;Va=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Wa=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.Xa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};
_.Ya=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.Za=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.ab=function(a,b){var c=_.$a(a,b,void 0);return 0>c?null:_.t(a)?a.charAt(c):a[c]};
_.$a=function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.bb=function(a,b){return 0<=Va(a,b)};_.db=function(a,b){var c=Va(a,b),d;(d=0<=c)&&_.cb(a,c);return d};_.cb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.eb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.fb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var hb=_.l.navigator;if(hb){var ib=hb.userAgent;if(ib){_.gb=ib;break a}}_.gb=""}_.w=function(a){return-1!=_.gb.indexOf(a)};var kb,lb,mb,ob;_.jb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};kb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};lb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};mb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.nb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};ob="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.pb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ob.length;f++)c=ob[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var qb=function(){return(_.w("Chrome")||_.w("CriOS"))&&!_.w("Edge")};var rb;rb=function(){return _.w("iPhone")&&!_.w("iPod")&&!_.w("iPad")};_.sb=function(){return _.w("Macintosh")};_.tb=function(){return _.w("Windows")};var ub,vb,yb,Cb,Db,Hb,Ib,Kb,Lb;ub=_.w("Opera");_.x=_.w("Trident")||_.w("MSIE");vb=_.w("Edge");_.wb=_.w("Gecko")&&!(-1!=_.gb.toLowerCase().indexOf("webkit")&&!_.w("Edge"))&&!(_.w("Trident")||_.w("MSIE"))&&!_.w("Edge");_.xb=-1!=_.gb.toLowerCase().indexOf("webkit")&&!_.w("Edge");yb=_.l.navigator||null;_.zb=yb&&yb.platform||"";_.Ab=_.sb();_.Bb=_.tb();Cb=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var Eb="",Fb=function(){var a=_.gb;if(_.wb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(vb)return/Edge\/([\d\.]+)/.exec(a);if(_.x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.xb)return/WebKit\/(\S+)/.exec(a);if(ub)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Fb&&(Eb=Fb?Fb[1]:"");if(_.x){var Gb=Cb();if(null!=Gb&&Gb>(0,window.parseFloat)(Eb)){Db=String(Gb);break a}}Db=Eb}Hb=Db;Ib={};_.Jb=function(a){return Ib[a]||(Ib[a]=0<=_.Ua(Hb,a))};Kb=_.l.document; Lb=Kb&&_.x?Cb()||("CSS1Compat"==Kb.compatMode?(0,window.parseInt)(Hb,10):5):void 0;
var Mb=_.w("Firefox"),Nb=rb()||_.w("iPod"),Ob=_.w("iPad"),Pb=_.w("Android")&&!(qb()||_.w("Firefox")||_.w("Opera")||_.w("Silk")),Qb=qb(),Rb=_.w("Safari")&&!(qb()||_.w("Coast")||_.w("Opera")||_.w("Edge")||_.w("Silk")||_.w("Android"))&&!(rb()||_.w("iPad")||_.w("iPod"));
var Sb=null;var Tb,Vb,Ub,Yb,Zb,Xb;Tb=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.Wb=function(a,b){var c=[];Ub(new Vb(b),a,c);return c.join("")};Vb=function(a){this.a=a};
Ub=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.za(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Ub(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),Xb(d,c),c.push(":"),Ub(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":Xb(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};Yb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Zb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; Xb=function(a,b){b.push('"',a.replace(Zb,function(a){var b=Yb[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Yb[a]=b);return b}),'"')};
var bc,cc,fc;_.y=function(){};_.$b="function"==typeof window.Uint8Array;_.z=function(a,b,c,d){a.b=null;b||(b=c?[c]:[]);a.I=c?String(c):void 0;a.h=0===c?-1:0;a.c=b;a:{if(a.c.length&&(b=a.c.length-1,(c=a.c[b])&&"object"==typeof c&&!_.za(c)&&!(_.$b&&c instanceof window.Uint8Array))){a.j=b-a.h;a.g=c;break a}a.j=Number.MAX_VALUE}a.A={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.h,a.c[c]=a.c[c]||_.ac):a.g[c]=a.g[c]||_.ac};_.ac=[];
_.A=function(a,b){if(b<a.j){var c=b+a.h,d=a.c[c];return d===_.ac?a.c[c]=[]:d}d=a.g[b];return d===_.ac?a.g[b]=[]:d};_.B=function(a,b,c){b<a.j?a.c[b+a.h]=c:a.g[b]=c};_.C=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.A(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};_.E=function(a,b,c){a.b||(a.b={});var d=c?_.D(c):c;a.b[b]=c;_.B(a,b,d)};bc=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.za(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){bc(a);return a.c};
cc=_.l.JSON&&_.l.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.y.prototype.l=_.$b?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Sb){Sb={};for(var a=0;65>a;a++)Sb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Sb,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;n||(q=64,h||(k=64));b.push(a[v],a[f],a[k],a[q])}return b.join("")};try{var b=cc.call(null,_.D(this),
dc)}finally{window.Uint8Array.prototype.toJSON=a}return b}:cc?function(){return cc.call(null,_.D(this),dc)}:function(){return _.Wb(_.D(this),dc)};var dc=function(a,b){if(_.xa(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.y.prototype.toString=function(){bc(this);return this.c.toString()};fc=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.ec(a[d],b[d]))return!1;return!0};
_.ec=function(a,b){if(a==b)return!0;if(!_.va(a)||!_.va(b)||a.constructor!=b.constructor)return!1;if(_.$b&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],k=b[c];h&&h.constructor==Object&&(d=h,h=void 0);k&&k.constructor==Object&&(e=k,k=void 0);if(!_.ec(h,k))return!1}return d||e?(d=d||{},e=e||{},fc(d,e)):!0}if(a.constructor=== Object)return fc(a,b);throw Error("e");};
_.F=function(){this.L=this.L;this.C=this.C};_.F.prototype.L=!1;_.F.prototype.Z=function(){this.L||(this.L=!0,this.B())};_.I=function(a,b){_.G(a,_.ua(_.H,b))};_.G=function(a,b,c){a.L?b.call(c):(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.r)(b,c):b))};_.F.prototype.B=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.Z&&a.Z()};
var gc=!_.x||9<=Number(Lb);!_.wb&&!_.x||_.x&&9<=Number(Lb)||_.wb&&_.Jb("1.9.1");_.x&&_.Jb("9");_.hc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.jc=function(){this.a="";this.c=_.ic;this.b=null};_.jc.prototype.Wa=!0;_.jc.prototype.La=function(){return this.b};_.jc.prototype.Xa=!0;_.jc.prototype.Va=function(){return this.a};_.ic={};_.kc=function(a,b){var c=new _.jc;c.a=a;c.b=b;return c};_.kc("<!DOCTYPE html>",0);_.kc("",0);_.lc=_.kc("<br>",0);
var rc,uc,tc;_.oc=function(a){return a?new _.mc(_.nc(a)):Da||(Da=new _.mc)};_.qc=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.pc(window.document,"*",a,b)[0];return d||null};
_.pc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.bb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.sc=function(a,b){_.jb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:rc.hasOwnProperty(d)?a.setAttribute(rc[d],b):_.Ea(d,"aria-")||_.Ea(d,"data-")?a.setAttribute(d,b):a[d]=b})};rc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
uc=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.ya(f)||_.va(f)&&0<f.nodeType?d(f):(0,_.u)(tc(f)?_.fb(f):f,d)}};_.vc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.nc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};tc=function(a){if(a&&"number"==typeof a.length){if(_.va(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.wa(a))return"function"==typeof a.item}return!1};
_.mc=function(a){this.a=a||_.l.document||window.document};_.g=_.mc.prototype;_.g.za=_.oc;_.g.H=function(a){return _.t(a)?this.a.getElementById(a):a};
_.g.qa=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!gc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Pa(h.name),'"');if(h.type){f.push(' type="',_.Pa(h.type),'"');var k={};_.pb(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.t(h)?f.className=h:_.za(h)?f.className=h.join(" "):_.sc(f,h));2<e.length&&uc(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var wc="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},xc=function(){};xc.prototype.next=function(){throw wc;};xc.prototype.la=function(){return this};
var yc=function(a){if(a instanceof xc)return a;if("function"==typeof a.la)return a.la(!1);if(_.ya(a)){var b=0,c=new xc;c.next=function(){for(;;){if(b>=a.length)throw wc;if(b in a)return a[b++];b++}};return c}throw Error("i");},zc=function(a,b){if(_.ya(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==wc)throw c;}else{a=yc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==wc)throw c;}}},Ac=function(a){if(_.ya(a))return _.fb(a);a=yc(a);var b=[];zc(a,function(a){b.push(a)});return b};
_.Bc=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.Bc?(c=a.X(),d=a.V()):(c=mb(a),d=lb(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.Bc.prototype.V=function(){Cc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.Bc.prototype.X=function(){Cc(this);return this.a.concat()};_.Ec=function(a,b){return Dc(a.b,b)};
_.Bc.prototype.clear=function(){this.b={};this.g=this.c=this.a.length=0};_.Bc.prototype.remove=function(a){return Dc(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&Cc(this),!0):!1};var Cc=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Dc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Dc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.g=_.Bc.prototype;
_.g.get=function(a,b){return Dc(this.b,a)?this.b[a]:b};_.g.set=function(a,b){Dc(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};_.g.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.g.clone=function(){return new _.Bc(this)};_.g.la=function(a){Cc(this);var b=0,c=this.g,d=this,e=new xc;e.next=function(){if(c!=d.g)throw Error("j");if(b>=d.a.length)throw wc;var e=d.a[b++];return a?e:d.b[e]};return e}; var Dc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Gc;_.Fc=function(a){if(a.V&&"function"==typeof a.V)return a.V();if(_.t(a))return a.split("");if(_.ya(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return lb(a)};
Gc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ya(a)||_.t(a))(0,_.u)(a,b,void 0);else{var c;if(a.X&&"function"==typeof a.X)c=a.X();else if(a.V&&"function"==typeof a.V)c=void 0;else if(_.ya(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=mb(a);for(var d=_.Fc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Hc=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};Hc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Ic=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var Mc;_.Jc=[];_.Kc=[];_.Lc=!1;Mc=function(a){_.Jc[_.Jc.length]=a;if(_.Lc)for(var b=0;b<_.Kc.length;b++)a((0,_.r)(_.Kc[b].b,_.Kc[b]))};var Nc,Pc,Qc,Oc;Nc=function(a){_.l.setTimeout(function(){throw a;},0)};_.Rc=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));c=Oc(c);!_.wa(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.w("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Pc||(Pc=Qc()),Pc(c)):_.l.setImmediate(c)};
Qc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.w("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.w("Trident")&&!_.w("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.gb;c.gb=null;a()}};return function(a){d.next={gb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Oc=function(a){return a};Mc(function(a){Oc=a});
var Sc=function(){this.b=this.a=null},Uc=new Hc(function(){return new Tc},function(a){a.reset()},100);Sc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Tc=function(){this.next=this.b=this.a=null};Tc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Tc.prototype.reset=function(){this.next=this.b=this.a=null};
var Vc,Wc,Xc,Yc,$c;_.Zc=function(a,b){Vc||Wc();Xc||(Vc(),Xc=!0);var c=Yc,d=Uc.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d};Wc=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);Vc=function(){a.then($c)}}else Vc=function(){_.Rc($c)}};Xc=!1;Yc=new Sc;$c=function(){for(var a;a=Yc.remove();){try{a.a.call(a.b)}catch(b){Nc(b)}Ic(Uc,a)}Xc=!1};
var ad=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},bd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ed,fd,gd,md,qd,cd,td,pd,nd;_.dd=function(a,b){this.a=0;this.l=void 0;this.g=this.b=this.c=null;this.h=this.j=!1;if(a!=_.Aa)try{var c=this;a.call(b,function(a){cd(c,2,a)},function(a){cd(c,3,a)})}catch(d){cd(this,3,d)}};ed=function(){this.next=this.context=this.b=this.g=this.a=null;this.c=!1};ed.prototype.reset=function(){this.context=this.b=this.g=this.a=null;this.c=!1};fd=new Hc(function(){return new ed},function(a){a.reset()},100);gd=function(a,b,c){var d=fd.get();d.g=a;d.b=b;d.context=c;return d};
_.hd=function(a){if(a instanceof _.dd)return a;var b=new _.dd(_.Aa);cd(b,2,a);return b};_.jd=function(){var a,b=new _.dd(function(b){a=b});return new id(b,a)};_.dd.prototype.then=function(a,b,c){return _.kd(this,_.wa(a)?a:null,_.wa(b)?b:null,c)};ad(_.dd);_.dd.prototype.C=function(a){0==this.a&&_.Zc(function(){var b=new ld(a);md(this,b)},this)};
md=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.c||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?md(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):nd(c),od(c,e,3,b)))}a.c=null}else cd(a,3,b)};qd=function(a,b){a.b||2!=a.a&&3!=a.a||pd(a);a.g?a.g.next=b:a.b=b;a.g=b};
_.kd=function(a,b,c,d){var e=gd(null,null,null);e.a=new _.dd(function(a,h){e.g=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof ld?h(b):a(e)}catch(q){h(q)}}:h});e.a.c=a;qd(a,e);return e.a};_.dd.prototype.w=function(a){this.a=0;cd(this,2,a)};_.dd.prototype.F=function(a){this.a=0;cd(this,3,a)};
cd=function(a,b,c){0==a.a&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.rd(c,a.w,a.F,a)||(a.l=c,a.a=b,a.c=null,pd(a),3!=b||c instanceof ld||sd(a,c)))};_.rd=function(a,b,c,d){if(a instanceof _.dd)return qd(a,gd(b||_.Aa,c||null,d)),!0;if(bd(a))return a.then(b,c,d),!0;if(_.va(a))try{var e=a.then;if(_.wa(e))return td(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
td=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};pd=function(a){a.j||(a.j=!0,_.Zc(a.v,a))};nd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};_.dd.prototype.v=function(){for(var a;a=nd(this);)od(this,a,this.a,this.l);this.j=!1};
var od=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,ud(b,c,d);else try{b.c?b.g.call(b.context):ud(b,c,d)}catch(e){vd.call(null,e)}Ic(fd,b)},ud=function(a,b,c){2==b?a.g.call(a.context,c):a.b&&a.b.call(a.context,c)},sd=function(a,b){a.h=!0;_.Zc(function(){a.h&&vd.call(null,b)})},vd=Nc,ld=function(a){_.Ca.call(this,a)};_.p(ld,_.Ca);ld.prototype.name="cancel";var id=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.wd=function(a,b){this.v=[];this.M=a;this.I=b||null;this.j=this.c=!1;this.g=void 0;this.J=this.O=this.F=!1;this.w=0;this.a=null;this.C=0};_.wd.prototype.l=function(a){if(this.c)this.g instanceof _.wd&&this.g.l();else{if(this.a){var b=this.a;delete this.a;a?b.l(a):(b.C--,0>=b.C&&b.l())}this.M?this.M.call(this.I,this):this.J=!0;this.c||this.K(new _.xd)}};_.wd.prototype.A=function(a,b){this.F=!1;yd(this,a,b)};
var yd=function(a,b,c){a.c=!0;a.g=c;a.j=!b;zd(a)},Bd=function(a){if(a.c){if(!a.J)throw new Ad;a.J=!1}};_.wd.prototype.b=function(a){Bd(this);yd(this,!0,a)};_.wd.prototype.K=function(a){Bd(this);yd(this,!1,a)};_.Dd=function(a,b,c){_.Cd(a,b,null,c)};_.Cd=function(a,b,c,d){a.v.push([b,c,d]);a.c&&zd(a)};_.wd.prototype.then=function(a,b,c){var d,e,f=new _.dd(function(a,b){d=a;e=b});_.Cd(this,d,function(a){a instanceof _.xd?f.C():e(a)});return f.then(a,b,c)};ad(_.wd);
_.Ed=function(a,b){b instanceof _.wd?_.Dd(a,(0,_.r)(b.h,b)):_.Dd(a,function(){return b})};_.wd.prototype.h=function(a){var b=new _.wd;_.Cd(this,b.b,b.K,b);a&&(b.a=this,this.C++);return b};
var Fd=function(a){return(0,_.Za)(a.v,function(a){return _.wa(a[1])})},zd=function(a){if(a.w&&a.c&&Fd(a)){var b=a.w,c=Gd[b];c&&(_.l.clearTimeout(c.a),delete Gd[b]);a.w=0}a.a&&(a.a.C--,delete a.a);for(var b=a.g,d=c=!1;a.v.length&&!a.F;){var e=a.v.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var k=f.call(e||a.I,b);_.m(k)&&(a.j=a.j&&(k==b||k instanceof Error),a.g=b=k);if(bd(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.F=!0}catch(n){b=n,a.j=!0,Fd(a)||(c=!0)}}a.g=b;d&&(k=(0,_.r)(a.A,
a,!0),d=(0,_.r)(a.A,a,!1),b instanceof _.wd?(_.Cd(b,k,d),b.O=!0):b.then(k,d));c&&(b=new Hd(b),Gd[b.a]=b,a.w=b.a)},Ad=function(){_.Ca.call(this)};_.p(Ad,_.Ca);Ad.prototype.message="Deferred has already fired";Ad.prototype.name="AlreadyCalledError";_.xd=function(){_.Ca.call(this)};_.p(_.xd,_.Ca);_.xd.prototype.message="Deferred was canceled";_.xd.prototype.name="CanceledError";var Hd=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a}; Hd.prototype.c=function(){delete Gd[this.a];throw this.b;};var Gd={};
var Id=!_.x||9<=Number(Lb),Jd=_.x&&!_.Jb("9");!_.xb||_.Jb("528");_.wb&&_.Jb("1.9b")||_.x&&_.Jb("8")||ub&&_.Jb("9.5")||_.xb&&_.Jb("528");_.wb&&!_.Jb("8")||_.x&&_.Jb("9");_.J=function(a,b){this.type="undefined"!=typeof _.Kd&&a instanceof _.Kd?String(a):a;this.c=this.target=b;this.g=!1;this.lb=!0};_.J.prototype.l=function(){this.g=!0};_.J.prototype.b=function(){this.lb=!1};var Ld=function(a){Ld[" "](a);return a};Ld[" "]=_.Aa;_.Md=function(a,b){try{return Ld(a[b]),!0}catch(c){}return!1};var Nd=function(a,b){_.J.call(this,a?a.type:"");this.c=this.target=null;this.keyCode=this.clientY=this.clientX=0;this.C=this.v=this.h=this.j=!1;this.a=this.state=null;if(a){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.c=b;var d=a.relatedTarget;d&&_.wb&&_.Md(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=
void 0!==c.clientY?c.clientY:c.pageY);this.keyCode=a.keyCode||0;this.j=a.ctrlKey;this.h=a.altKey;this.v=a.shiftKey;this.C=a.metaKey;this.state=a.state;this.a=a;a.defaultPrevented&&this.b()}};_.p(Nd,_.J);Nd.prototype.l=function(){Nd.D.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; Nd.prototype.b=function(){Nd.D.b.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Jd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Od="closure_listenable_"+(1E6*Math.random()|0),Pd=function(a){return!(!a||!a[Od])},Qd=0;var Rd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.ya=!!d;this.Na=e;this.key=++Qd;this.removed=this.Ja=!1},Sd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Na=null};var Td=function(a){this.src=a;this.a={};this.b=0},Vd=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var k=Ud(b,c,e,f);-1<k?(a=b[k],d||(a.Ja=!1)):(a=new Rd(c,a.src,h,!!e,f),a.Ja=d,b.push(a));return a};Td.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Ud(e,b,c,d);return-1<b?(Sd(e[b]),_.cb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Wd=function(a,b){var c=b.type;c in a.a&&_.db(a.a[c],b)&&(Sd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Td.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Sd(d[e]);delete this.a[c];this.b--}return b};
var Xd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Ud(a,c,d,e));return-1<b?a[b]:null},Yd=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return kb(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].ya))return!0;return!1})},Ud=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.ya==!!c&&f.Na==d)return e}return-1};
var Zd,$d,ae,de,fe,ke,ge,me,le,he,ee,ne,ce;Zd="closure_lm_"+(1E6*Math.random()|0);$d={};ae=0;_.be=function(a,b,c,d,e){if(_.za(b)){for(var f=0;f<b.length;f++)_.be(a,b[f],c,d,e);return null}c=ce(c);return Pd(a)?a.listen(b,c,d,e):de(a,b,c,!1,d,e)};
de=function(a,b,c,d,e,f){if(!b)throw Error("k");var h=!!e,k=ee(a);k||(a[Zd]=k=new Td(a));c=Vd(k,b,c,d,e,f);if(c.proxy)return c;d=fe();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ge(b.toString()),d);else throw Error("l");ae++;return c};fe=function(){var a=he,b=Id?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.ie=function(a,b,c,d,e){if(_.za(b)){for(var f=0;f<b.length;f++)_.ie(a,b[f],c,d,e);return null}c=ce(c);return Pd(a)?a.Ma(b,c,d,e):de(a,b,c,!0,d,e)};_.je=function(a,b,c,d,e){if(_.za(b))for(var f=0;f<b.length;f++)_.je(a,b[f],c,d,e);else c=ce(c),Pd(a)?a.wa(b,c,d,e):a&&(a=ee(a))&&(b=Xd(a,b,c,!!d,e))&&ke(b)};
ke=function(a){if(!_.xa(a)&&a&&!a.removed){var b=a.src;if(Pd(b))Wd(b.c,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ya):b.detachEvent&&b.detachEvent(ge(c),d);ae--;(c=ee(b))?(Wd(c,a),0==c.b&&(c.src=null,b[Zd]=null)):Sd(a)}}};ge=function(a){return a in $d?$d[a]:$d[a]="on"+a};me=function(a,b,c,d){var e=!0;if(a=ee(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.ya==c&&!f.removed&&(f=le(f,d),e=e&&!1!==f)}return e};
le=function(a,b){var c=a.listener,d=a.Na||a.src;a.Ja&&ke(a);return c.call(d,b)};
he=function(a,b){if(a.removed)return!0;if(!Id){var c=b||_.Ba("window.event"),d=new Nd(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.c;f;f=f.parentNode)c.push(f);for(var f=a.type,h=c.length-1;!d.g&&0<=h;h--){d.c=c[h];var k=me(c[h],f,!0,d),e=e&&k}for(h=0;!d.g&&h<c.length;h++)d.c=c[h],k=me(c[h],f,!1,d),e=e&&k}return e}return le(a,new Nd(b,this))}; ee=function(a){a=a[Zd];return a instanceof Td?a:null};ne="__closure_events_fn_"+(1E9*Math.random()>>>0);ce=function(a){if(_.wa(a))return a;a[ne]||(a[ne]=function(b){return a.handleEvent(b)});return a[ne]};Mc(function(a){he=a(he)});
_.K=function(){_.F.call(this);this.c=new Td(this);this.ia=this;this.F=null};_.p(_.K,_.F);_.K.prototype[Od]=!0;_.K.prototype.J=function(a){this.F=a};_.K.prototype.removeEventListener=function(a,b,c,d){_.je(this,a,b,c,d)};
_.L=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);var d=a.ia,e=b,f=e.type||e;if(_.t(e))e=new _.J(e,d);else if(e instanceof _.J)e.target=e.target||d;else{var h=e,e=new _.J(f,d);_.pb(e,h)}var h=!0,k;if(c)for(var n=c.length-1;!e.g&&0<=n;n--)k=e.c=c[n],h=k.ea(f,!0,e)&&h;e.g||(k=e.c=d,h=k.ea(f,!0,e)&&h,e.g||(h=k.ea(f,!1,e)&&h));if(c)for(n=0;!e.g&&n<c.length;n++)k=e.c=c[n],h=k.ea(f,!1,e)&&h;return h};_.g=_.K.prototype;
_.g.B=function(){_.K.D.B.call(this);this.c&&this.c.removeAll(void 0);this.F=null};_.g.listen=function(a,b,c,d){return Vd(this.c,String(a),b,!1,c,d)};_.g.Ma=function(a,b,c,d){return Vd(this.c,String(a),b,!0,c,d)};_.g.wa=function(a,b,c,d){return this.c.remove(String(a),b,c,d)}; _.g.ea=function(a,b,c){a=this.c.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.ya==b){var h=f.listener,k=f.Na||f.src;f.Ja&&Wd(this.c,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.lb};
var oe=function(){};oe.prototype.a=null;var qe=function(a){var b;(b=a.a)||(b={},pe(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var re,se=function(){};_.p(se,oe);var te=function(a){return(a=pe(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},pe=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("m");}return a.b};re=new se;
_.ue=function(a,b){_.K.call(this);this.h=a||1;this.g=b||_.l;this.j=(0,_.r)(this.v,this);this.l=(0,_.pa)()};_.p(_.ue,_.K);_.ue.prototype.b=!1;_.ue.prototype.a=null;_.ue.prototype.setInterval=function(a){this.h=a;this.a&&this.b?(this.stop(),_.ve(this)):this.a&&this.stop()};
_.ue.prototype.v=function(){if(this.b){var a=(0,_.pa)()-this.l;0<a&&a<.8*this.h?this.a=this.g.setTimeout(this.j,this.h-a):(this.a&&(this.g.clearTimeout(this.a),this.a=null),_.L(this,"tick"),this.b&&(this.a=this.g.setTimeout(this.j,this.h),this.l=(0,_.pa)()))}};_.ve=function(a){a.b=!0;a.a||(a.a=a.g.setTimeout(a.j,a.h),a.l=(0,_.pa)())};_.ue.prototype.stop=function(){this.b=!1;this.a&&(this.g.clearTimeout(this.a),this.a=null)};_.ue.prototype.B=function(){_.ue.D.B.call(this);this.stop();delete this.g}; _.we=function(a,b,c){if(_.wa(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("n");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.xe=function(a){_.l.clearTimeout(a)};
var ye=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,ze=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var Ae=function(a){_.K.call(this);this.ka=new _.Bc;this.I=a||null;this.b=!1;this.A=this.a=null;this.O="";this.j=0;this.h="";this.g=this.M=this.v=this.K=!1;this.l=0;this.w=null;this.aa="";this.T=this.W=!1},Be,Ce,Le,Je,He,Me,Ne;_.p(Ae,_.K);Be=/^https?$/i;Ce=["POST","PUT"];_.De=[];_.Ee=function(a,b,c,d,e,f,h){var k=new Ae;_.De.push(k);b&&k.listen("complete",b);k.Ma("ready",k.ja);f&&(k.l=Math.max(0,f));h&&(k.W=h);k.send(a,c,d,e)};Ae.prototype.ja=function(){this.Z();_.db(_.De,this)};
Ae.prototype.send=function(a,b,c,d){if(this.a)throw Error("o`"+this.O+"`"+a);b=b?b.toUpperCase():"GET";this.O=a;this.h="";this.j=0;this.K=!1;this.b=!0;this.a=this.I?te(this.I):te(re);this.A=this.I?qe(this.I):qe(re);this.a.onreadystatechange=(0,_.r)(this.$,this);try{this.M=!0,this.a.open(b,String(a),!0),this.M=!1}catch(f){Fe(this,f);return}a=c||"";var e=this.ka.clone();d&&Gc(d,function(a,b){e.set(b,a)});d=_.ab(e.X(),Ge);c=_.l.FormData&&a instanceof _.l.FormData;!_.bb(Ce,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.aa&&(this.a.responseType=this.aa);"withCredentials"in this.a&&this.a.withCredentials!==this.W&&(this.a.withCredentials=this.W);try{He(this),0<this.l&&((this.T=Ie(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.r)(this.Y,this)):this.w=_.we(this.Y,this.l,this)),this.v=!0,this.a.send(a),this.v=!1}catch(f){Fe(this,f)}};
var Ie=function(a){return _.x&&_.Jb(9)&&_.xa(a.timeout)&&_.m(a.ontimeout)},Ge=function(a){return"content-type"==a.toLowerCase()};Ae.prototype.Y=function(){"undefined"!=typeof _.na&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.L(this,"timeout"),this.a&&this.b&&(this.b=!1,this.g=!0,this.a.abort(),this.g=!1,this.j=8,_.L(this,"complete"),_.L(this,"abort"),Je(this)))};
var Fe=function(a,b){a.b=!1;a.a&&(a.g=!0,a.a.abort(),a.g=!1);a.h=b;a.j=5;Ke(a);Je(a)},Ke=function(a){a.K||(a.K=!0,_.L(a,"complete"),_.L(a,"error"))};Ae.prototype.B=function(){this.a&&(this.b&&(this.b=!1,this.g=!0,this.a.abort(),this.g=!1),Je(this,!0));Ae.D.B.call(this)};Ae.prototype.$=function(){this.L||(this.M||this.v||this.g?Le(this):this.R())};Ae.prototype.R=function(){Le(this)};
Le=function(a){if(a.b&&"undefined"!=typeof _.na&&(!a.A[1]||4!=Me(a)||2!=Ne(a)))if(a.v&&4==Me(a))_.we(a.$,0,a);else if(_.L(a,"readystatechange"),4==Me(a)){a.b=!1;try{if(_.Oe(a))_.L(a,"complete"),_.L(a,"success");else{a.j=6;var b;try{b=2<Me(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Ne(a)+"]";Ke(a)}}finally{Je(a)}}};Je=function(a,b){if(a.a){He(a);var c=a.a,d=a.A[0]?_.Aa:null;a.a=null;a.A=null;b||_.L(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
He=function(a){a.a&&a.T&&(a.a.ontimeout=null);_.xa(a.w)&&(_.xe(a.w),a.w=null)};_.Oe=function(a){var b=Ne(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.O).match(ye)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!Be.test(a?a.toLowerCase():"");c=b}return c};Me=function(a){return a.a?a.a.readyState:0};Ne=function(a){try{return 2<Me(a)?a.a.status:-1}catch(b){return-1}}; _.Pe=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Mc(function(a){Ae.prototype.R=a(Ae.prototype.R)});
var Re;_.M=function(a){_.F.call(this);this.v=a;this.g={}};_.p(_.M,_.F);var Qe=[];_.M.prototype.listen=function(a,b,c,d){_.za(b)||(b&&(Qe[0]=b.toString()),b=Qe);for(var e=0;e<b.length;e++){var f=_.be(a,b[e],c||this.handleEvent,d||!1,this.v||this);if(!f)break;this.g[f.key]=f}return this};_.Se=function(a,b,c,d){Re(a,b,c,d,void 0)};Re=function(a,b,c,d,e,f){if(_.za(c))for(var h=0;h<c.length;h++)Re(a,b,c[h],d,e,f);else(b=_.ie(b,c,d||a.handleEvent,e,f||a.v||a))&&(a.g[b.key]=b)};
_.M.prototype.wa=function(a,b,c,d,e){if(_.za(b))for(var f=0;f<b.length;f++)this.wa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.v||this,c=ce(c),d=!!d,b=Pd(a)?Xd(a.c,String(b),c,d,e):a?(a=ee(a))?Xd(a,b,c,d,e):null:null,b&&(ke(b),delete this.g[b.key]);return this};_.M.prototype.removeAll=function(){_.jb(this.g,function(a,b){this.g.hasOwnProperty(b)&&ke(a)},this);this.g={}};_.M.prototype.B=function(){_.M.D.B.call(this);this.removeAll()};_.M.prototype.handleEvent=function(){throw Error("p");};
var Te=function(){};Te.prototype.g=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var Ue=function(a){(a?a:function(){}).Ib=!0};_.Ve=function(){};_.p(_.Ve,Te);_.Ve.prototype.b=function(a){return a};Ue(_.Ve.prototype.b);_.Ve.prototype.c=function(){return!0};Ue(_.Ve.prototype.c);var We=function(a){_.z(this,a,0,null)};_.p(We,_.y);var Xe;Xe=function(a,b){var c=new We;_.B(c,1,b);_.B(c,2,a);return c};_.Ye=Xe("?",0);_.Ze=Xe("q",1);_.bf=Xe("<",2);_.cf=Xe(">",3);_.df=Xe("~",4);_.ef=Xe("s",5);_.N=function(a,b,c){this.c=a;this.b=b||null;this.a=c||[]};_.N.prototype.toString=function(){return this.c};var ff,gf,hf,kf,mf,vf,nf,pf,of,sf,qf,lf,wf;_.Q=function(a,b){this.b=this.C=this.h="";this.g=null;this.l=this.a="";this.j=!1;var c;a instanceof _.Q?(this.j=_.m(b)?b:a.j,ff(this,a.h),this.C=a.C,this.b=a.b,gf(this,a.g),this.a=a.a,hf(this,a.c.clone()),_.jf(this,a.l)):a&&(c=String(a).match(ye))?(this.j=!!b,ff(this,c[1]||"",!0),this.C=kf(c[2]||""),this.b=kf(c[3]||"",!0),gf(this,c[4]),this.a=kf(c[5]||"",!0),hf(this,c[6]||"",!0),_.jf(this,c[7]||"",!0)):(this.j=!!b,this.c=new lf(null,0,this.j))};
_.Q.prototype.toString=function(){var a=[],b=this.h;b&&a.push(mf(b,nf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(mf(b,nf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(mf(c,"/"==c.charAt(0)?of:pf,!0));(c=this.c.toString())&&a.push("?",c);(c=this.l)&&a.push("#",mf(c,qf));return a.join("")};_.Q.prototype.clone=function(){return new _.Q(this)};
ff=function(a,b,c){a.h=c?kf(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};gf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("s`"+b);a.g=b}else a.g=null};hf=function(a,b,c){b instanceof lf?(a.c=b,rf(a.c,a.j)):(c||(b=mf(b,sf)),a.c=new lf(b,0,a.j))};_.R=function(a,b,c){a.c.set(b,c)};_.jf=function(a,b,c){a.l=c?kf(b):b};_.tf=function(a){return a instanceof _.Q?a.clone():new _.Q(a,void 0)};
_.uf=function(a,b){a instanceof _.Q||(a=_.tf(a));b instanceof _.Q||(b=_.tf(b));var c=a,d=b,e=c.clone(),f=!!d.h;f?ff(e,d.h):f=!!d.C;f?e.C=d.C:f=!!d.b;f?e.b=d.b:f=null!=d.g;var h=d.a;if(f)gf(e,d.g);else if(f=!!d.a)if("/"!=h.charAt(0)&&(c.b&&!c.a?h="/"+h:(c=e.a.lastIndexOf("/"),-1!=c&&(h=e.a.substr(0,c+1)+h))),c=h,".."==c||"."==c)h="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var h=_.Ea(c,"/"),c=c.split("/"),k=[],n=0;n<c.length;){var q=c[n++];"."==q?h&&n==c.length&&k.push(""):".."==q?((1<
k.length||1==k.length&&""!=k[0])&&k.pop(),h&&n==c.length&&k.push("")):(k.push(q),h=!0)}h=k.join("/")}else h=c;f?e.a=h:f=""!==d.c.toString();f?hf(e,kf(d.c.toString())):f=!!d.l;f&&_.jf(e,d.l);return e};kf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};mf=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,vf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
vf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};nf=/[#\/\?@]/g;pf=/[\#\?:]/g;of=/[\#\?]/g;sf=/[\#\?@]/g;qf=/#/g;lf=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c};wf=function(a){a.a||(a.a=new _.Bc,a.b=0,a.c&&ze(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));wf(a);a.c=null;var d=xf(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b=a.b+1}))};
lf.prototype.remove=function(a){wf(this);a=xf(this,a);return _.Ec(this.a,a)?(this.c=null,this.b=this.b-this.a.get(a).length,this.a.remove(a)):!1};lf.prototype.clear=function(){this.a=this.c=null;this.b=0};var yf=function(a,b){wf(a);b=xf(a,b);return _.Ec(a.a,b)};lf.prototype.X=function(){wf(this);for(var a=this.a.V(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
lf.prototype.V=function(a){wf(this);var b=[];if(_.t(a))yf(this,a)&&(b=_.eb(b,this.a.get(xf(this,a))));else{a=this.a.V();for(var c=0;c<a.length;c++)b=_.eb(b,a[c])}return b};lf.prototype.set=function(a,b){wf(this);this.c=null;a=xf(this,a);yf(this,a)&&(this.b=this.b-this.a.get(a).length);this.a.set(a,[b]);this.b=this.b+1;return this};lf.prototype.get=function(a,b){var c=a?this.V(a):[];return 0<c.length?String(c[0]):b};
_.zf=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(xf(a,b),_.fb(c)),a.b=a.b+c.length)};lf.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.V(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.c=a.join("&")};
lf.prototype.clone=function(){var a=new lf;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};var xf=function(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c},rf=function(a,b){b&&!a.g&&(wf(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.zf(this,e,a))},a));a.g=b};
_.Ve.D||_.p(_.Ve,Te);_.Af=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
_.Bf=function(a){_.z(this,a,"uv_i_sc",null)};_.p(_.Bf,_.y);_.Bf.messageId="uv_i_sc";_.Cf=function(a){_.z(this,a,"uv_qm",null)};_.p(_.Cf,_.y);_.Cf.messageId="uv_qm";_.Df=function(a){_.z(this,a,"uv_r_rdm",null)};_.p(_.Df,_.y);_.Df.messageId="uv_r_rdm";_.Ef=function(a){_.z(this,a,"uv_r_rr",null)};_.p(_.Ef,_.y);_.Ef.messageId="uv_r_rr";_.Ff=function(a){_.z(this,a,"uv_r_frm",null)};_.p(_.Ff,_.y);_.Ff.messageId="uv_r_frm";_.Gf=function(a){_.z(this,a,0,null)};_.p(_.Gf,_.y);
var If=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("u");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,q,v,O){if("%"==q)return"%";var P=c.shift();if("undefined"==typeof P)throw Error("v");arguments[0]=P;return Hf[q].apply(null,arguments)})},Hf={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Qa(" ",Number(c)-a.length):Qa(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Qa(" ",a):f+Qa(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return Hf.f((0,window.parseInt)(a,10),b, c,d,0,f,h,k)}};Hf.i=Hf.d;Hf.u=Hf.d;
_.S=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=If("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+If(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+If.apply({},c)))};
_.Jf=new _.N("pVbxBc");_.Kf=new _.N("S53Hlb");_.Lf=new _.N("Eyr1Zc");_.U=new _.N("nED8Yb");_.Mf=new _.N("xclgJb");_.Nf=new _.N("Qz9Lj");_.Pf=function(a){_.z(this,a,"h_cd",Of)};_.p(_.Pf,_.y);var Of=[1,4,5];_.Pf.messageId="h_cd";_.Qf=function(a){_.z(this,a,"h_icr",null)};_.p(_.Qf,_.y);_.Qf.messageId="h_icr";_.Qf.prototype.a=function(){return _.A(this,1)};_.Rf=function(a){_.z(this,a,"h_opc",null)};_.p(_.Rf,_.y);_.Rf.messageId="h_opc";_.Sf=function(a){_.z(this,a,"h_sc",null)};_.p(_.Sf,_.y);_.Sf.messageId="h_sc";_.Tf=function(a){_.z(this,a,"h_po",null)};_.p(_.Tf,_.y);_.Tf.messageId="h_po";_.Uf=function(a){return _.uf(a,"/webchat/host-js")};_.Vf=function(a){var b=_.Uf(_.A(a,2));_.R(b,"prop",_.Af(27));_.R(b,"b",1);_.R(b,"hl",_.A(a,3));_.A(a,4)&&_.R(b,"jsmode",_.A(a,4));_.R(b,"zx",_.Sa());return b.toString()};_.Wf=function(a){_.z(this,a,"h_ssf",null)};_.p(_.Wf,_.y);_.Wf.messageId="h_ssf";_.Xf=function(a,b){this.l=a||"e";this.g=null!=a&&"p"==a?"e":"p";this.c=this.h=null;this.j=b||"u";this.a=this.C=null;this.b=[]};_.Xf.prototype.message=function(){var a={};a.i=this.a;a.m=this.b;a.r=this.j;a.o=this.C;a.s=this.c;a.st=this.g;a.d=this.h;a.dt=this.l;return a};_.Xf.prototype.message=_.Xf.prototype.message;_.Xf.prototype.source=function(){return this.c};_.Xf.prototype.target=function(){return this.h};_.Xf.prototype.content=function(){return this.b};
_.Zf=function(a){_.z(this,a,"h_exts",Yf)};_.p(_.Zf,_.y);var Yf=[2];_.Zf.messageId="h_exts";var $f=function(a,b){_.J.call(this,a,b);this.N=b};_.p($f,_.J);var ag=function(a){_.z(this,a,"capi_md1571",null)};_.p(ag,_.y);ag.messageId="capi_md1571";var bg={bb:0,tc:1,sc:2,ab:3,Pa:4},cg=function(a){_.z(this,a,0,null)};_.p(cg,_.y);var eg=function(){for(var a=10,b=dg,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},dg="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.fg=function(a,b){_.F.call(this);this.j=b||eg();this.g=this.a="";this.b=this.c=null;this.l=a;this.h=new _.M(this);_.I(this,this.h);this.h.listen(window,"message",this.v)};_.p(_.fg,_.F);_.fg.prototype.fa=function(a,b,c){this.g=a;this.c=b;this.b=c};
_.fg.prototype.v=function(a){a=a.a;var b;b=a.origin;this.c&&this.c!=a.source||"*"!=this.g&&this.g!=b?b=!1:this.b?(b=(new _.Q(b)).b,b=_.Fa(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.t(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.za(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new ag(c),_.A(c,1)==this.j)){b=_.A(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.g&&this.c||this.fa(a.origin,a.source);
1==_.A(c,2)?this.send(2):this.l(c,a)}}};_.fg.prototype.send=function(a,b,c){if(this.a&&this.c){b=b||new ag;_.B(b,3,this.j);_.B(b,1,this.a);_.B(b,2,a);var d=JSON.stringify(_.D(b)),e=this.c,f=this.g;_.x?_.we(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var gg=function(a,b,c,d,e){this.c=_.jd();this.a=new _.fg((0,_.r)(this.h,this),d);this.a.fa(a,b,e);this.a.a=c;this.b=new _.ue(50);_.ve(this.b);_.be(this.b,"tick",this.g,!1,this);this.g();a=this.c.a;b=this.j;b=gd(b,b,this);b.c=!0;qd(a,b)};gg.prototype.j=function(){_.H(this.a);_.je(this.b,"tick",this.g,!1,this);_.H(this.b)};gg.prototype.g=function(){this.a.send(1)};gg.prototype.h=function(a,b){2==_.A(a,2)&&this.c.b(b.origin)};
var hg=function(a,b,c){_.F.call(this);this.b=a;a=_.A(b,3);b=_.A(b,1);this.a=new _.fg((0,_.r)(this.c,this),b);this.a.a=a;c&&this.a.fa(c.origin,c.source);_.I(this,this.a)};_.p(hg,_.F);hg.prototype.send=function(a){var b=new ag;_.E(b,4,a);this.a.send(bg.bb,b)};hg.prototype.connect=function(a,b){this.a.fa(a,b);this.a.send(bg.ab)};hg.prototype.c=function(a){_.A(a,2)==bg.bb&&(a=_.C(a,cg,4),this.b(a))};hg.prototype.g=_.Aa;
var jg=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.c=null;c?(this.b=c.ports[0],ig(this)):(this.a=new _.fg(_.Aa,_.A(b,1)),a=_.A(b,3),this.a.a=a)};_.p(jg,_.F);jg.prototype.B=function(){jg.D.B.call(this);this.b&&this.b.close();_.H(this.a)};jg.prototype.g=function(){this.c=new _.M(this);_.I(this,this.c);ig(this)};jg.prototype.send=function(a){this.b.postMessage(_.D(a))};
jg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;ig(this);var d=this.a;this.a=null;c=c.port2;d.fa(a,b);d.send(bg.Pa,void 0,[c]);_.H(d)};var ig=function(a){a.b&&a.c&&(a.c.listen(a.b,"message",a.j),a.b.start())};jg.prototype.j=function(a){a=a.a;var b;try{b=new cg(a.data)}catch(c){return}this.h(b)};
var kg=function(a,b,c){var d=!1;_.m(_.A(b,2))?_.A(b,2)==bg.Pa&&(d=!0):d=Qb;return d?new jg(a,b,c):new hg(a,b,c)};var og;_.lg=function(){_.K.call(this);this.h=null;this.l=!1;this.j=[];this.g=[];_.G(this,this.w,this);this.b=null};_.p(_.lg,_.K);_.lg.prototype.w=function(){for(;this.g.length;)this.g.shift()()};_.ng=function(a){a.w();a.j=[];a.b=new _.wd;a.g.push((0,_.r)(a.b.l,a.b));a.l=!1;_.Dd(a.b.h(),function(a){(Yd(this.c)||this.F)&&mg(this);this.g.push(_.ua(_.H,a))},a)};_.g=_.lg.prototype;_.g.sendMessage=function(a){this.da(_.D(a))};_.g.da=function(a){if(this.b){var b=new cg;_.B(b,1,a);_.Dd(this.b.h(),function(a){a.send(b)})}};
_.g.$a=function(a){this.h=a;_.G(this,function(){this.h=null},this);mg(this)};_.g.G=function(){return this};_.g.fa=function(a,b,c){this.a.fa(a,b,c)};_.pg=function(a,b,c,d){_.ng(a);og(a,b,c,d).then(function(a){var d=new ag;_.B(d,1,a.pc);_.B(d,3,c);d=kg((0,_.r)(this.v,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};og=function(a,b,c,d){var e=eg();b=(new gg("*",b,c,e,d)).c.a;a.g.push((0,_.r)(b.C,b));return b.then(function(a){return{pc:e,origin:a}})};
_.lg.prototype.I=function(a,b){if(_.A(a,2)==bg.ab||_.A(a,2)==bg.Pa)_.H(this.a),this.a=null,this.b.b(kg((0,_.r)(this.v,this),a,b))};_.lg.prototype.v=function(a){this.j.push(a);this.A()};_.lg.prototype.A=function(){for(;qg(this););};var qg=function(a){if(a.L||!a.l||0==a.j.length)return!1;var b=_.A(a.j.shift(),1);a.h&&a.h.da(b);_.L(a,new $f(b[0],b));return!0},mg=function(a){a.l||(a.l=!0,a.b&&_.Dd(a.b.h(),function(a){a.g();_.we(this.A,0,this)},a))}; _.lg.prototype.listen=function(a,b,c,d){mg(this);return _.lg.D.listen.call(this,a,b,c,d)};_.lg.prototype.Ma=function(a,b,c,d){mg(this);return _.lg.D.Ma.call(this,a,b,c,d)};_.lg.prototype.J=function(a){mg(this);return _.lg.D.J.call(this,a)};
var rg=function(a){this.b=a;this.g="empty";this.a=null;this.c={}};rg.prototype.setVersion=function(a){this.g=a;return this};rg.prototype.va=function(a){this.a=a;return this};rg.prototype.Za=function(a){this.c=_.nb(a);return this};var sg=function(){};var tg=function(){};_.p(tg,sg);tg.prototype.clear=function(){var a=Ac(this.la(!0)),b=this;(0,_.u)(a,function(a){b.remove(a)})};var ug=function(a){this.a=a};_.p(ug,tg);_.g=ug.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.la=function(a){var b=0,c=this.a,d=new xc;d.next=function(){if(b>=c.length)throw wc;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var vg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.p(vg,ug);var xg=function(a,b){this.c=a;this.a=[];this.b=null;b&&(this.b=new vg);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=Tb(c)||[]}catch(d){}}c=!1;_.za(this.a)||(this.a=[],c=!0);for(;this.a.length>this.c;)this.a.shift(),c=!0;c&&wg(this)},wg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Wb(a.a))}catch(b){}};
var yg=function(a){_.F.call(this);this.a=a;this.h=!1};_.p(yg,_.F);yg.prototype.setEnabled=function(a){this.h=a};var zg=function(a){return(a=a.exec(_.gb))?a[1]:""},Ag=function(){if(Mb)return zg(/Firefox\/([0-9.]+)/);if(_.x||vb||ub)return Hb;if(Qb)return zg(/Chrome\/([0-9.]+)/);if(Rb&&!(rb()||_.w("iPad")||_.w("iPod")))return zg(/Version\/([0-9.]+)/);if(Nb||Ob){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.gb);if(a)return a[1]+"."+a[2]}else if(Pb)return(a=zg(/Android\s+([0-9.]+)/))?a:zg(/Version\/([0-9.]+)/);return""}();
var V=function(a){yg.call(this,a);this.w=100;this.v={};this.S=null;this.c="";this.F=!0;this.j=10;this.b=null;this.g=!1};_.p(V,yg);V.prototype.pb=function(a){this.F=a;return this};V.prototype.setUseLocalStorage=V.prototype.pb;V.prototype.oc=function(a){this.j=Math.min(a,100);return this};V.prototype.setMaxErrorsPerHour=V.prototype.oc;V.prototype.nb=function(a){this.w=a;return this};V.prototype.setGlobalSampling=V.prototype.nb;V.prototype.eb=function(a,b){this.v[a]=b;return this};
V.prototype.addPerErrorMessageSampling=V.prototype.eb;V.prototype.mb=function(a){this.S=a;return this};V.prototype.setCallback=V.prototype.mb;V.prototype.nc=function(a){this.c=a;return this};V.prototype.setClientId=V.prototype.nc;V.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.A.bind(this);this.setEnabled(!0);return!0};V.prototype.enable=V.prototype.enable;
V.prototype.jb=function(a,b,c,d,e){var f=_.tf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.wa(this.S)||this.S(f.a,a,b,c,d,e))if(h=this.g){h=Object.keys(this.v);for(var k=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(k=this.v[q])}if(h=(100*Math.random()).toFixed(6)>=this.w*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new xg(this.j,this.F));if(null===this.b)h=0;else{a:{h=this.b;k=(0,_.pa)();if(h.a.length==h.c)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
wg(h);h=!0}h=!h}h=!h&&this.g}}h&&(h=_.nb(this.a.c),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",ub?k="Opera":_.x?k="Internet Explorer":Mb?k="Firefox":Qb?k="Chrome":Rb&&(k="Safari"),h.browser=k,h.browser_version=Ag,h.os=_.w("CrOS")?"Chrome OS":_.w("Linux")?"Linux":_.tb()?"Windows":_.w("Android")?"Android":rb()?"iPhone":_.w("iPad")?"iPad":_.w("iPod")?"iPod":_.sb()?"Mac":"Unknown",k=_.gb,n="",_.tb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):rb()||_.w("iPad")||
_.w("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.sb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.w("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.w("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ga(this.c)||(h.guid=this.c),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.g,b=
Bg(h),e=null!=e?_.Ra(e.stack):"",_.Ga(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),Cg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ra(this.a.a),_.Ga(a)||(f.version=a),Cg(this,"https://clients2.google.com/cr/staging_perf",Bg(f)))};V.prototype.reportError=V.prototype.jb;V.prototype.A=function(a,b,c,d,e){this.jb(a,b,c,d,e);null!=this.l&&_.wa(this.l)&&this.l(a,b,c,d,e)};
var Bg=function(a){var b="",c;for(c in a)b+=_.Ga(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},Cg=function(a,b,c,d){d=d||"";var e=_.Ga(d)?{}:{"Content-Type":"text/plain"};_.Ee(b+c,a.J.bind(a,b),"POST",d,e,6E4,!0)};V.prototype.J=function(a,b){_.Oe(b.target)};
var Dg=function(a){yg.call(this,a);this.S=null;this.b=0};_.p(Dg,yg);Dg.prototype.mb=function(a){this.S=a;return this};var Eg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Dg.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.ue(6E4);_.I(this,a);var b=new _.M(this);_.I(this,b);b.listen(a,"tick",this.c);_.ve(a);this.setEnabled(!0);return!0}return!1};
Dg.prototype.c=function(){this.b+=6E4;for(var a="",b=0;b<Eg.length;++b)if(this.b==Eg[b].age){a=Eg[b].name;break}if(""!=a){var b=Fg.test(_.gb)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.tf(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.Ra(this.a.a);_.Ga(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.wa(this.S)&&this.S(b,a[d].displayName,a[d].value);_.Ee("https://clients2.google.com/cr/staging_perf"+c,Gg,"POST","",null,6E4,!0)}}};var Gg=function(a){_.Oe(a.target)},Fg=/(x86_64|Win64)/;
var Hg=function(a){_.F.call(this);this.b=new rg(a);this.a={}};_.p(Hg,_.F);_.ta("webmonitoring.Monitoring",Hg);Hg.prototype.setVersion=function(a){this.b.setVersion(a);return this};Hg.prototype.setVersion=Hg.prototype.setVersion;Hg.prototype.va=function(a){this.b.va(a);return this};Hg.prototype.setChannel=Hg.prototype.va;Hg.prototype.Za=function(a){this.b.Za(a);return this};Hg.prototype.setContext=Hg.prototype.Za;Hg.prototype.Ka=function(){null!=this.a[2]||(this.a[2]=new V(this.b));return this.a[2]}; Hg.prototype.createJsErrorsReporter=Hg.prototype.Ka;
var Ig=function(a){Hg.call(this,a)};_.p(Ig,Hg);Ig.prototype.setVersion=function(a){return Ig.D.setVersion.call(this,a)};Ig.prototype.va=function(a){return Ig.D.va.call(this,a)};Ig.prototype.Ka=function(){var a=Ig.D.Ka.call(this);a.g=!0;return a};_.Jg=function(){var a=new Ig("Google_Hangouts_Chrome");a.va(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Dg(a.b));a.a[1].enable();a.Ka().pb(!1).nb(100).eb("Script error.",0).enable()};var Kg=function(a,b){this.c=a;this.b=b;this.constructor.fb||(this.constructor.fb={});this.constructor.fb[this.toString()]=this};Kg.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var Lg=function(a,b){Kg.call(this,a,b)};_.p(Lg,Kg);var Mg=function(a){this.a=a};new Mg("lib");var Ng,Vg,Wg,Xg;_.Og=function(a){_.F.call(this);this.g={};this.j={};this.l={};this.a={};this.c={};this.J={};this.v=a?a.G():new _.K;this.R=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.c=a.c):(0,_.pa)();a=Ng(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Og,_.F);_.Pg=.05>Math.random();Ng=function(a){for(;a.b;)a=a.b;return a};_.Og.prototype.get=function(a){var b=_.Qg(this,a);if(null==b)throw new Rg(a);return b};
_.Qg=function(a,b){for(var c=a;c;c=c.b){if(c.L)throw Error("w");if(c.g[b])return c.g[b][0];if(c.J[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("x`"+b);_.Sg(a,b,c);return c}return null};
_.Og.prototype.F=function(a,b){var c=_.Qg(this,a);if(null==c){if(this.c[a]){var d=this.c[a].h();_.Dd(d,(0,_.r)(this.F,this,a,b));return d}throw new Tg(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.Sa?(d=new _.wd,_.Ed(d,c.Sa()),d.b(c),_.Dd(d,(0,_.r)(this.w,this,a)),d):this.w(a)};_.Og.prototype.w=function(a){this.c[a]&&delete this.c[a];return this.get(a)};_.Og.prototype.K=function(a,b,c){return c instanceof _.xd?c:new Ug(a,b,c)};
_.Sg=function(a,b,c,d){if(a.L)d||_.H(c);else{a.g[b]=[c,!d];d=Vg(a,a,b);for(var e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};Vg=function(a,b,c){var d=[],e=a.a[c];e&&(_.Wa(e,function(a){var c;a:{for(c=a.Ra;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.db(e,a))}),0==e.length&&delete a.a[c]);return d};Wg=function(a,b){a.a&&Gc(a.a,function(a,d,e){_.Wa(a,function(d){d.Ra==b&&_.db(a,d)});0==a.length&&delete e[d]})};
_.Og.prototype.I=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].Ra==this&&c[d].d==b){_.cb(c,d);break}0==c.length&&delete this.a[a]}};_.Og.prototype.B=function(){if(Ng(this)==this){var a=this.h;if(a)for(;a.length;)a[0].Z()}else for(var a=Ng(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.g)a=this.g[c],a[1]&&a[0].Z&&a[0].Z();this.g=null;this.R&&this.v.Z();Wg(this,this);this.a=null;_.H(this.O);this.J=this.O=null;_.Og.D.B.call(this)};
_.Og.prototype.G=function(){return this.v};var Rg=function(a){_.Ca.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.p(Rg,_.Ca);var Ug=function(a,b,c){_.Ca.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.p(Ug,_.Ca);var Tg=function(a,b,c){_.Ca.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.p(Tg,_.Ca); Xg=new Mg("fva");_.Yg=new Lg(Xg,1);

}catch(e){_._DumpException(e)}
try{
var qp=/\s*;\s*/,rp=function(){return[]},sp=function(a){a=(a.a.cookie||"").split(qp);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}},tp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.ba[c[0]].prototype[a].apply(this,arguments)}:b[a].Kb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]];if(n=n?n[a].apply(n,d):this.ba[c[e]].prototype[a].apply(this,d)){d=n;break a}}d=!1}return d}:b[a].Jb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]],n=n?n[a].apply(n,d):this.ba[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break a}}d=void 0}return d}:b[a].$b?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.ba[c[e]].prototype[a].apply(this,d)}}:
e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var q=this.a[c[n]];e.push(q?q[a].apply(q,d):this.ba[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Kb||b[a].Jb||b[a].$b?e=null:e=rp;return e},up=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},vp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ya(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},
wp=[1],xp=function(a,b){return a.c.get(b)},yp=function(a){this.a=a||{cookie:""}};_.g=yp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("q`"+a);if(/[;\r\n]/.test(b))throw Error("r`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.pa)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(qp),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.g.X=function(){return sp(this).keys};_.g.V=function(){return sp(this).values};_.g.clear=function(){for(var a=sp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var zp=function(a){return this.Ta.g(a)},Ap=function(a){_.z(this,a,"ci:ec",null)};
_.p(Ap,_.y);Ap.messageId="ci:ec";
var Bp={a:_.Ye,F:_.Ze,v:_.bf,w:_.cf,C:_.df,J:_.ef},Cp=function(a){var b=a.ra,c=function(a){c.D.constructor.call(this,a);var b=this.ba.length;this.a=[];for(var d=0;d<b;++d)this.ba[d].Cc||(this.a[d]=new this.ba[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ra){b.ba&&vp(d,b.ba);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.wa(e[f])&&e[f]!==b){var h=!!e[f].Ib,k=up(f,e,d,h);(h=tp(f,e,k,h))&&(c.prototype[f]=h)}}a=a.D&&a.D.constructor}c.prototype.ba=d;return c},Dp=function(a){_.z(this,a,"capi:r_rstr",
null)};_.p(Dp,_.y);Dp.messageId="capi:r_rstr";var Ep=function(a){_.z(this,a,"capi:r_recl",null)};_.p(Ep,_.y);Ep.messageId="capi:r_recl";var Fp=function(a){_.z(this,a,"capi:r_clre",null)};_.p(Fp,_.y);Fp.messageId="capi:r_clre";
var Gp=function(a,b){var c={};try{c=JSON.parse(b)||{}}catch(e){}for(var d in c)switch(d){case "r":a.j=c[d];break;case "i":a.a=c[d];break;case "m":a.b=c[d];break;case "o":a.C=c[d];break;case "s":a.c=c[d];break;case "d":a.h=c[d];break;case "st":a.g=c[d];break;case "dt":a.l=c[d]}},Hp=function(a){_.z(this,a,0,wp)};_.p(Hp,_.y);var Ip=function(a){_.z(this,a,"uv_r_hrd",null)};_.p(Ip,_.y);Ip.messageId="uv_r_hrd";var Jp=function(a){_.z(this,a,"uv_r_rrr",null)};_.p(Jp,_.y);Jp.messageId="uv_r_rrr";
var Kp=function(a){_.z(this,a,"uv_r_rdr",null)};_.p(Kp,_.y);Kp.messageId="uv_r_rdr";
var Lp=function(a,b,c){if(!this.Ta){for(var d=this.constructor;d&&!d.ra;)d=d.D&&d.D.constructor;d.ra.hb||(d.ra.hb=Cp(d));this.Ta=new d.ra.hb(this);this.g||(this.g=zp)}var e=this.Ta.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ea(e,"https://talkgadget.google.com/talkgadget/")){var d=(new yp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.bb(f,d)&&h.test(d)&&(e=_.tf(e),
e=_.tf("https://"+d+e.a).toString())}this.pa=e;this.c=c||new Ap;a.notificationsOnly&&_.B(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=xp(new _.Q(window.location.href),"authuser"),null!=c&&(this.b=c));this.v=a.clientUrl||"notifierclient";c=xp(_.tf(this.v),"authuser");null!=c&&(this.b=c);this.Qa=a.propertyName||"Google Talk";this.F=a.cssUrl;this.locale=a.locale;this.C=a.debug;this.Ca=a.userJid;this.Ga=a.uiVersion;this.Ub=null!=a.rosterExpanded?a.rosterExpanded:!0;this.Y=a.hostLogMinValue;
this.Da=a.hideChat;this.Nb=a.refresh;this.O=a.hideProfileCard;this.W=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.R=a.hideRecentConversations;this.M=a.hideOTR;this.Hb=a.hostServerMessageCallback||!1;this.aa=a.isCentralRoster;this.Mb=a.isFullFrame||!1;this.Tb=a.rosterClass||"talk_roster";this.Vb=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.xa=a.parentToken;
this.Rb=b||!1;this.j=_.m(a.isRtl)?a.isRtl:_.hc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in Bp)b.push(_.D(Bp[k]))}this.A=a.entityId;this.Ha=a.useQuasarPanels||!1;this.Ea=a.silent||!1;this.Lb=a.ignoreCentralRoster||!1;this.Qb=a.lazy||!1;this.Gb=a.handleProfileLinks||!1;this.$=a.hostSettings;this.l=a.screen;this.J=a.docsConfig;this.Ob=a.jsmode;this.ka=a.moleWidth;this.ja=a.moleHeight;this.ia=a.minimizedMoleHeight||36;this.Wb=a.derp;this.Fa=window.location.protocol+
"//"+window.location.host;this.h="";this.K=a.optOutAllowed;this.I=a.legacyTalkSignedIn;this.Ia=a.useSpareMole;this.w=a.conversationId};Lp.ra=_.Ve;var Mp=function(a){_.z(this,a,0,null)};_.p(Mp,_.y);var Np=function(a){_.z(this,a,0,null)};_.p(Np,_.y);var Op=function(a){_.z(this,a,0,null)};_.p(Op,_.y);var Pp=function(a){_.z(this,a,0,null)};_.p(Pp,_.y);var Qp=function(a){return null==_.A(a,8)?"0":_.A(a,8)},Rp=function(a){_.z(this,a,"h_cc",null)};_.p(Rp,_.y);Rp.messageId="h_cc";
var Sp=function(a,b){_.kd(a,null,b,void 0)},Tp=function(a,b,c){_.rd(a,b,c,null)||_.Zc(_.ua(b,a))},Up=function(a){return new _.dd(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,n;k<a.length;k++)n=a[k],Tp(n,_.ua(f,k),h);else b(e)})},Vp=function(a){_.ea();_.ca();_.ea();_.ca();_.ea();var b=a[window.Symbol.iterator];if(b)return b.call(a);var c=0;return{next:function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}};
var Wp=function(a){this.a=a;_.x||(delete this.a.lpu,delete this.a.ppu)},Xp=["cn","tp"],Yp=function(a,b){var c;if(_.wa(window.document.postMessage)||_.wa(window.postMessage)||_.x&&window.postMessage)c=1;else if(_.wb)c=2;else{var d;if(d=_.x){d=!1;try{c=window.opener,window.opener={},d=_.Md(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Wp(d)};_.ta("GTalk_IFrameChannelConfig.build",Yp);
var Zp=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.c=new _.M(this);_.I(this,this.c);var f=_.gb;d=new _.Q(a.pa+a.v);var h=a.c;null!=_.A(h,2)&&_.A(h,2)||(_.R(d,"ts","0"),_.R(d,"re",a.Ub),_.R(d,"ref",a.Nb));_.R(d,"client","sm");_.R(d,"prop",a.Qa);_.R(d,"nav","true");_.R(d,"fid",a.a);a.C&&_.R(d,"debug",a.C);_.R(d,"os",_.zb);_.R(d,"stime",c);a.Da&&_.R(d,"hc",a.Da);for(c=0;c<Xp.length;++c);b=_.Wb(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Wb(_.D(a.c)));a.l&&_.R(d,"screen",a.l);-1!=
f.indexOf("MSIE")&&_.R(d,"ua",f);a.xa&&_.R(d,"pvt",a.xa);a.Hb&&_.R(d,"hsmc","true");_.m(a.Y)&&_.R(d,"logl",a.Y);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Q(window.location.href);"false"==xp(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Ob)&&_.R(d,"jsmode",f);(f=xp(b,"cssmode"))&&_.R(d,"cssmode",f);(f=xp(b,"convid"))&&_.R(d,"convid",f);if(f=b.c.V("convp"))_.za(f)||(f=[String(f)]),_.zf(d.c,"convp",f);(f=
xp(b,"smexp"))&&_.R(d,"smexp",f);f=b.c.V("mods");a.Qb&&f.push("lazy");e&&(f=_.eb(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.pa||0>a.pa.indexOf("/u/"))(e=xp(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=xp(b,"eid");_.Ga(_.Ra(e))||_.R(d,"eid",e);_.Ga(_.Ra(this.a.A))||_.R(d,"eid",this.a.A);null!=this.a.position&&_.R(d,"pos",this.a.position);_.m(a.Ga)&&_.R(d,"uiv",this.a.Ga);a.F&&_.R(d,"css",a.F);e=a.locale||xp(b,"hl");null!=e&&_.R(d,"hl",e);_.m(a.Ca)&&_.R(d,"uj",a.Ca);
null!=a.O&&_.R(d,"hpc",a.O);null!=a.W&&_.R(d,"hsm",a.W);null!=a.T&&_.R(d,"hro",a.T);null!=a.R&&_.R(d,"hrc",a.R);null!=a.M&&_.R(d,"hotr",a.M);null!=a.aa&&_.R(d,"pop",a.aa);a.Rb&&_.R(d,"pal","1");null!=a.Ha&&_.R(d,"uqp",a.Ha);null!=a.K&&_.R(d,"gooa",a.K);null!=a.I&&_.R(d,"gltsi",a.I);null!=a.Ia&&_.R(d,"gusm",a.Ia);null!=a.Ea&&_.R(d,"sl",a.Ea);a.Lb&&_.R(d,"icr","1");a.Gb&&_.R(d,"hpl","1");a.$&&_.R(d,"hs",a.$);a.J&&_.R(d,"dc",_.Wb(_.D(a.J)));null!=a.ka&&_.R(d,"molew",a.ka);null!=a.ja&&_.R(d,"moleh",a.ja);
null!=a.ia&&_.R(d,"mmoleh",a.ia);a.Wb&&_.R(d,"derp","1");a.h&&_.R(d,"fcho",a.h);null!=a.Fa&&_.R(d,"two",a.Fa);null!=a.w&&_.R(d,"convid",a.w);_.R(d,"host","1");_.R(d,"zx",_.Sa());this.g=d.toString()};_.p(Zp,_.F);
var $p=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Tb,a.b.body.appendChild(e));a=(0,_.r)(function(){var a="";this.a.Mb||(a="height:400px");var b=this.b.createElement("iframe");_.sc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});_.qc("talk_loading_msg",e)||_.vc(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.Se(this.c,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat","*");d(a)}); k.src=this.g.toString();c()},a);window.setTimeout(a,0)};
var aq=new _.N("q"),bq=new _.N("r"),cq=new _.N("s");var dq=function(a){_.K.call(this);this.a=a};_.p(dq,_.K);var eq=function(a){_.M.call(this);var b=a.get(cq);this.a=new dq(a.get(_.Lf));this.listen(b.G(),"h_opc",this.c);this.listen(b.G(),"h_sc",this.h);this.listen(b.G(),"h_po",this.j);this.listen(b.G(),"h_icr",this.b)};_.p(eq,_.M);eq.prototype.c=function(a){var b=this.a;a=_.C(new _.Rf(a.N),_.Pf,1);var c=new _.Rf;_.E(c,1,a);b.a.da(_.D(c))};eq.prototype.h=function(a){var b=this.a;a=_.A(new _.Sf(a.N),1);var c=new _.Sf;_.B(c,1,a);b.a.da(_.D(c))}; eq.prototype.j=function(a){var b=this.a;a=_.A(new _.Tf(a.N),1);var c=new _.Tf;_.B(c,1,a);b.a.da(_.D(c))};eq.prototype.b=function(a){var b=this.a;a=(new _.Qf(a.N)).a();var c=new _.Qf;_.B(c,1,a);b.a.da(_.D(c))};
var fq=function(a){_.z(this,a,"h_rha",null)};_.p(fq,_.y);fq.messageId="h_rha";var gq=function(a,b){_.F.call(this);this.a=new _.M(this);_.I(this,this.a);this.a.listen(a.G(),"h_ssf",function(a){a=_.A(new _.Wf(a.N),1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new fq;_.B(c,1,1);a.da(_.D(c))};_.p(gq,_.F);
var hq=function(a){_.F.call(this);this.a=a.get(cq);_.I(this,new gq(a.get(_.Lf),(0,_.r)(this.b,this)))};_.p(hq,_.F);hq.prototype.b=function(a){var b=new _.Wf;a&&(a=JSON.stringify(a),_.B(b,1,a));this.a.sendMessage(b)};var iq=function(a){_.M.call(this);this.b=a.get(cq);this.listen(this.b.G(),"uv_i_sc",this.c);this.a=null};_.p(iq,_.M);iq.prototype.c=function(a){if(this.a){var b="idle";1==_.A(new _.Bf(a.N),1)&&(b="active");this.a(b)}};var jq=function(a){_.K.call(this);this.a=a.get(cq);a=new _.M(this);_.I(this,a);a.listen(this.a.G(),"uv_r_frm",this.b);a.listen(this.a.G(),"uv_r_rdm",this.g)};_.p(jq,_.K);jq.prototype.reload=function(a){var b=new _.Ef;_.B(b,1,a);this.a.sendMessage(b)};jq.prototype.b=function(a){a=new _.Ff(a.N);_.L(this,new kq(!!_.A(a,1)))};jq.prototype.g=function(a){a=new _.Df(a.N);_.L(this,new lq(_.A(a,1)))};var kq=function(a){_.J.call(this,"uv_r_frm");this.a=a};_.p(kq,_.J); var lq=function(a){_.J.call(this,"uv_r_rdm");this.a=a};_.p(lq,_.J);
var mq=function(a){var b=_.l.GTalkNotifier;return b?_.hd(b):new _.dd(function(c,d){var e=_.we(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Vf(a);f.addEventListener("load",function(){_.xe(e);(b=_.l.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.xe(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var nq=function(a){_.K.call(this);this.a=a.get(_.U);a=new _.M(this);_.I(a,a);a.listen(this.a.G(),"capi:r_clre",this.h);a.listen(this.a.G(),"capi:r_rrst",this.b);a.listen(this.a.G(),"capi:r_rers",this.g)};_.p(nq,_.K);nq.prototype.h=function(a){a=new Fp(a.N);_.L(this,new oq(_.C(a,Hp,1)))};nq.prototype.g=function(){_.L(this,"I")};nq.prototype.b=function(){_.L(this,"H")};var oq=function(a){_.J.call(this,"G");this.a=a};_.p(oq,_.J);
var pq=function(a){_.M.call(this);this.b=a.get(_.Nf);this.a=a.get(aq);this.listen(this.a,"uv_r_rdm",this.Eb);this.listen(this.a,"uv_r_frm",this.Db);this.listen(this.b,"G",this.ic);this.listen(this.b,"H",this.Cb);this.listen(this.b,"I",this.Fb)};_.p(pq,_.M);_.g=pq.prototype;_.g.ic=function(a){a=(a=a.a)?[_.D(a)]:[void 0];this.a.reload(a)};_.g.Cb=function(){var a=this.a,b=new Kp;a.a.sendMessage(b)};_.g.Db=function(a){var b=this.b;a=!!a.a;var c=new Ep;_.B(c,1,!!a);b.a.sendMessage(c)}; _.g.Eb=function(a){if(a.a&&(a=a.a[0])){a=new Hp(a);var b=this.b,c=new Dp;_.E(c,1,a);b.a.sendMessage(c)}};_.g.Fb=function(){var a=this.a,b=new Jp;a.a.sendMessage(b)};
var qq=function(a){return new _.dd(function(b,c){_.Ee(_.uf(a,"/webchat/extension-start"),function(a){_.Oe(a.target)||c();try{var e=JSON.parse(_.Pe(a.target));b(new _.Zf(e))}catch(f){c(f.message)}})})};var rq=new _.N("t");var sq=function(a){_.J.call(this,a[0]);this.N=a};_.p(sq,_.J);var uq=function(a,b){_.F.call(this);this.v=(0,_.pa)();var c={},d;d=null==_.A(a,1)?"hangouts.google.com":_.A(a,1);var e="";0>d.indexOf("://")&&(e="https://",0<=d.indexOf(":")&&23!=_.A(a,2)&&27!=_.A(a,2)&&(e="http://"));-1!=d.indexOf("talkgadget.")?(c.clientBaseUrl=e+d+"/talkgadget/_/",c.clientUrl="chat"):(c.clientBaseUrl=e+d+"/webchat/u/"+Qp(a)+"/",c.clientUrl="load");c.authUser=Qp(a);c.propertyName=_.Af(_.A(a,2));c.locale=_.A(a,4);c.hideProfileCard=!0;c.parentToken=_.A(a,3);d=null==_.A(a,6)?!1:_.A(a,
6);c.isRtl=d;d=null==_.A(a,7)?!1:_.A(a,7);c.lazy=d;c.entityId=_.A(a,9);c.hostSettings=_.A(a,5);c.jsmode=_.A(a,11);d=null==_.A(a,13)?!1:_.A(a,13);c.isFullFrame=d;d=null==_.A(a,12)?"talk_roster":_.A(a,12);c.rosterId=d;d=null==_.A(a,15)?"gtn-roster-iframe-id-b":_.A(a,15);c.rosterIframeIdB=d;d=null==_.A(a,16)?!1:_.A(a,16);c.derp=!!d;d=_.C(a,Mp,14);null!=d&&(e=null==_.A(d,1)?!1:_.A(d,1),c.isCentralRoster=e,d=null==_.A(d,2)?!1:_.A(d,2),c.useQuasarPanels=d);d=_.C(a,Pp,10);null!=d&&(c.moleManagerLeftMargin=
_.A(d,1),c.moleManagerMiddleMargin=_.A(d,2),c.moleManagerRightMargin=_.A(d,3),c.moleManagerNoMoleAreaMargin=_.A(d,4),c.moleManagerBoundingElementId=_.A(d,5),c.moleWidth=_.A(d,6),c.moleHeight=_.A(d,7),c.minimizedMoleHeight=_.A(d,8));d=_.C(a,Op,18);null!=d&&(e=null==_.A(d,1)?!0:_.A(d,1),c.optOutAllowed=e,e=_.C(d,Np,3),null!=e&&(e=null==_.A(e,1)?!0:_.A(e,1),c.legacyTalkSignedIn=e),d=_.A(d,4),null!=d&&(c.useSpareMole=d));c.uiVersion=2;c.hideStatusMsgs=!0;c.hideRecentConversations=!0;d=new Ap;_.B(d,2,
!0);_.B(d,1,!0);_.B(d,3,!1);c.endpointConfig=d;d=null==_.A(a,17)?!1:_.A(a,17);c.ignoreAutomatedRoster=d;c.conversationId=_.A(a,19);this.g=c;c=this.a=new Lp(this.g,!0,this.g.endpointConfig);var f=this.a.pa;d=this.a.b;if(-1!=f.indexOf("talkgadget.")){var e=_.tf(f),h=e.a;if(0<=h.indexOf("/u/"))d=f;else{f=h.lastIndexOf("_/");if(0>f||f!=h.length-2)h+="_/";e.a="/u/"+d+h;d=e.toString()}}else d=f;c.pa=d;this.a.h=window.location.origin;this.b=null;this.l=new _.K;c=_.nb(this.g);c.endpointConfig=_.D(this.a.c);
this.h=new b(c,!0);this.j=new _.lg;_.I(this,this.j);tq(this)};_.p(uq,_.F);uq.prototype.sendMessage=function(a){this.da(_.D(a))};uq.prototype.da=function(a){this.c("_h",a)};uq.prototype.$a=function(a){this.b=a;_.G(this,function(){this.b=null},this)};uq.prototype.G=function(){return this.l};
var tq=function(a){var b=Yp(a.a.pa,a.a.a),b=new Zp(a.a,b,a.v,window.document);_.I(a,b);$p(b,a.a.Vb,function(){},function(){return vq(a)})},vq=function(a){_.pg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.c("_addClientMessageCallback",function(b){a.b&&a.b.da(b);_.L(a.l,new sq(b))});a.c("_rosterIframeLoaded")};uq.prototype.c=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var wq=function(a){_.z(this,a,"capi:id_sc",null)};_.p(wq,_.y);wq.messageId="capi:id_sc";var xq=function(a){_.K.call(this);var b=new _.M(this);_.I(b,b);this.a=a.get(_.U)};_.p(xq,_.K);xq.prototype.b=function(a){var b=new wq;switch(a){case "idle":_.B(b,1,0);break;case "active":_.B(b,1,1)}this.a.sendMessage(b)};var yq=function(a){_.z(this,a,"h_ext",null)};_.p(yq,_.y);yq.messageId="h_ext";var Aq=function(){_.M.call(this);_.S("Starting ...");this.a=new _.Og;_.I(this,this.a);this.j=null;this.h=[];this.listen(window,"unload",this.Z);this.c=new _.Gf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.A(this.c,1),b=new _.lg;_.ng(b);b.a=new _.fg((0,_.r)(b.I,b),a);b.a.fa("*",void 0,void 0);b.g.push(_.ua(_.H,b.a));this.b=b;_.Sg(this.a,cq,this.b);this.listen(this.b.G(),"uv_qm",this.l);zq(this)},Bq;_.p(Aq,_.M);
var Cq=function(a,b){null==a.h?b():a.h.push(b)},zq=function(a){_.S("Initializing ...");Sp(Up([qq(_.A(a.c,2)).then(a.w,void 0,a),mq(a.c)]).then(function(b){b=Vp(b);var c=b.next().value;b=b.next().value;if(a.L)b=null;else{var d=new Rp,e=_.tf(_.A(a.c,2)),f=e.b;null!=e.g&&(f+=":"+e.g);_.B(d,1,f);_.B(d,2,27);_.B(d,13,!0);_.B(d,17,!0);c=_.A(c,1);_.B(d,3,c);c=_.A(a.c,4);_.B(d,11,c);c=_.A(a.c,3)||"en";_.B(d,4,c);c=new Mp;_.B(c,2,!0);_.B(c,1,!0);_.E(d,14,c);b=new uq(d,b)}return b}).then(function(b){if(!a.L){b.$a(a.b);
a.b.$a(b);a.j=b;_.Sg(a.a,_.U,a.j);_.Sg(a.a,_.Lf,a.j);_.Sg(a.a,bq,a.j);_.I(a,new eq(a.a));b=new iq(a.a);_.Sg(a.a,rq,b);var c=new xq(a.a);_.Sg(a.a,_.Kf,c);c=(0,_.r)(c.b,c);b.a=c;_.I(a,new hq(a.a));b=new jq(a.a);_.Sg(a.a,aq,b);_.Sg(a.a,_.Nf,new nq(a.a));new pq(a.a);for(a.b.sendMessage(new Ip);a.h.length;)a.h.shift()();a.h=null}}),function(a){_.S("Failed to start : %s.",a||"")})};Aq.prototype.w=function(a){var b=this;return new _.dd(function(c,d){b.b.sendMessage(a);_.A(a,1)||d("Unauthenticated");c(a)})};
Aq.prototype.l=function(a){a=new _.Cf(a.N);var b=new _.Xf;Gp(b,_.A(a,1));"onSendHostMessage"==b.a&&Cq(this,(0,_.r)(function(){var a=new yq,d=b.content().toString();_.B(a,1,d);this.j.sendMessage(a)},this))};_.ta("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Jg();if(!_.m(Bq)||null==Bq||Bq.L)Bq=new Aq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
