"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca,ea,da,ha,ia,ka,la;
for(_.g,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this,ca=function(){ca=function(){};ba.Symbol||(ba.Symbol=da)},ea=0,da=function(a){return"jscomp_symbol_"+(a||"")+ea++},_.ga=function(){ca();var a=ba.Symbol.iterator;a||(a=ba.Symbol.iterator=
ba.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return _.fa(this)}});_.ga=function(){}},_.fa=function(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},ha=function(a){_.ga();a={next:a};a[ba.Symbol.iterator]=function(){return this};return a},ia=ba,ka=["String","prototype","repeat"],la=0;la<ka.length-1;la++){var ma=ka[la];ma in ia||(ia[ma]={});ia=ia[ma]}
var na=ka[ka.length-1],oa=ia[na],pa=oa?oa:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};pa!=oa&&null!=pa&&aa(ia,na,{configurable:!0,writable:!0,value:pa});_.qa=_.qa||{};_.l=this;_.ra="closure_uid_"+(1E9*Math.random()>>>0);_.sa=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var ta,ua;_.m=function(a){return void 0!==a};ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ua=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.va=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ac=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.wa=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.xa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ua:ta;return _.r.apply(null,arguments)};
_.ya=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.za=function(a){return"function"==_.va(a)};_.Aa=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.Ba=function(a){var b=_.va(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Ca=function(a){return"array"==_.va(a)};_.Da=function(){};_.Ea=function(a){a=a.split(".");for(var b=_.l,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}; _.Fa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Fa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.Fa,Error);_.Fa.prototype.name="CustomError";
var Ga;var Ka,Ma,Na,Oa,Pa,Qa,Ra,La,Ta,Wa;_.Ha=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ia=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ja=function(a){return/^[\s\xa0]*$/.test(a)};Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Sa=function(a){if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ra,"&#0;"));return a};Ma=/&/g;Na=/</g;Oa=/>/g;Pa=/"/g;Qa=/'/g;Ra=/\x00/g;La=/[\x00&<>"']/;Ta=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ua=function(a){return null==a?"":String(a)};_.Va=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.sa)()).toString(36)};
_.Xa=function(a,b){for(var c=0,d=Ka(String(a)).split("."),e=Ka(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];n=/(\d*)(\D*)(.*)/.exec(n)||["","","",""];if(0==k[0].length&&0==n[0].length)break;c=Wa(0==k[1].length?0:(0,window.parseInt)(k[1],10),0==n[1].length?0:(0,window.parseInt)(n[1],10))||Wa(0==k[2].length,0==n[2].length)||Wa(k[2],n[2]);k=k[3];n=n[3]}while(0==c)}return c}; Wa=function(a,b){return a<b?-1:a>b?1:0};
var Ya;Ya=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Za=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.$a=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};
_.ab=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.bb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.db=function(a,b){var c=_.cb(a,b,void 0);return 0>c?null:_.t(a)?a.charAt(c):a[c]};
_.cb=function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.eb=function(a,b){return 0<=Ya(a,b)};_.gb=function(a,b){var c=Ya(a,b),d;(d=0<=c)&&_.fb(a,c);return d};_.fb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.hb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.ib=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var kb=_.l.navigator;if(kb){var lb=kb.userAgent;if(lb){_.jb=lb;break a}}_.jb=""}_.w=function(a){return-1!=_.jb.indexOf(a)};var nb,ob,pb,rb;_.mb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};nb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};ob=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};pb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.qb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};rb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.sb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<rb.length;f++)c=rb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var tb=function(){return(_.w("Chrome")||_.w("CriOS"))&&!_.w("Edge")};var ub;ub=function(){return _.w("iPhone")&&!_.w("iPod")&&!_.w("iPad")};_.vb=function(){return _.w("Macintosh")};_.wb=function(){return _.w("Windows")};var xb=function(a){xb[" "](a);return a};xb[" "]=_.Da;_.yb=function(a,b){try{return xb(a[b]),!0}catch(c){}return!1};_.zb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var Ab,Bb,Eb,Ib,Jb,Nb,Ob,Qb,Rb;Ab=_.w("Opera");_.x=_.w("Trident")||_.w("MSIE");Bb=_.w("Edge");_.Cb=_.w("Gecko")&&!(-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.w("Edge"))&&!(_.w("Trident")||_.w("MSIE"))&&!_.w("Edge");_.Db=-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.w("Edge");Eb=_.l.navigator||null;_.Fb=Eb&&Eb.platform||"";_.Gb=_.vb();_.Hb=_.wb();Ib=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var Kb="",Lb=function(){var a=_.jb;if(_.Cb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Bb)return/Edge\/([\d\.]+)/.exec(a);if(_.x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Db)return/WebKit\/(\S+)/.exec(a);if(Ab)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lb&&(Kb=Lb?Lb[1]:"");if(_.x){var Mb=Ib();if(null!=Mb&&Mb>(0,window.parseFloat)(Kb)){Jb=String(Mb);break a}}Jb=Kb}Nb=Jb;Ob={};_.Pb=function(a){return _.zb(Ob,a,function(){return 0<=_.Xa(Nb,a)})};Qb=_.l.document; Rb=Qb&&_.x?Ib()||("CSS1Compat"==Qb.compatMode?(0,window.parseInt)(Nb,10):5):void 0;
var Sb=_.w("Firefox"),Tb=ub()||_.w("iPod"),Ub=_.w("iPad"),Vb=_.w("Android")&&!(tb()||_.w("Firefox")||_.w("Opera")||_.w("Silk")),Wb=tb(),Xb=_.w("Safari")&&!(tb()||_.w("Coast")||_.w("Opera")||_.w("Edge")||_.w("Silk")||_.w("Android"))&&!(ub()||_.w("iPad")||_.w("iPod"));
var Yb=null;var Zb,$b,bc,ac,ec,fc,dc;Zb=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};$b=function(a){a=String(a);if(Zb(a))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.cc=function(a,b){var c=[];ac(new bc(b),a,c);return c.join("")};
bc=function(a){this.a=a};
ac=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.Ca(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],ac(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),dc(d,c),c.push(":"),ac(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":dc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ec={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};fc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; dc=function(a,b){b.push('"',a.replace(fc,function(a){var b=ec[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ec[a]=b);return b}),'"')};
var ic,jc,mc;_.y=function(){};_.gc="function"==typeof window.Uint8Array;_.z=function(a,b,c,d){a.b=null;b||(b=c?[c]:[]);a.H=c?String(c):void 0;a.h=0===c?-1:0;a.c=b;a:{if(a.c.length&&(b=a.c.length-1,(c=a.c[b])&&"object"==typeof c&&!_.Ca(c)&&!(_.gc&&c instanceof window.Uint8Array))){a.j=b-a.h;a.g=c;break a}a.j=Number.MAX_VALUE}a.A={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.h,a.c[c]=a.c[c]||_.hc):a.g[c]=a.g[c]||_.hc};_.hc=[];
_.A=function(a,b){if(b<a.j){var c=b+a.h,d=a.c[c];return d===_.hc?a.c[c]=[]:d}d=a.g[b];return d===_.hc?a.g[b]=[]:d};_.B=function(a,b,c){b<a.j?a.c[b+a.h]=c:a.g[b]=c};_.C=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.A(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};_.E=function(a,b,c){a.b||(a.b={});var d=c?_.D(c):c;a.b[b]=c;_.B(a,b,d)};ic=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.Ca(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){ic(a);return a.c};
jc=_.l.JSON&&_.l.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.y.prototype.l=_.gc?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Yb){Yb={};for(var a=0;65>a;a++)Yb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Yb,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;n||(q=64,h||(k=64));b.push(a[v],a[f],a[k],a[q])}return b.join("")};try{var b=jc.call(null,_.D(this),
kc)}finally{window.Uint8Array.prototype.toJSON=a}return b}:jc?function(){return jc.call(null,_.D(this),kc)}:function(){return _.cc(_.D(this),kc)};var kc=function(a,b){if(_.Aa(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.y.prototype.toString=function(){ic(this);return this.c.toString()};mc=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.lc(a[d],b[d]))return!1;return!0};
_.lc=function(a,b){if(a==b)return!0;if(!_.ya(a)||!_.ya(b)||a.constructor!=b.constructor)return!1;if(_.gc&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],k=b[c];h&&h.constructor==Object&&(d=h,h=void 0);k&&k.constructor==Object&&(e=k,k=void 0);if(!_.lc(h,k))return!1}return d||e?(d=d||{},e=e||{},mc(d,e)):!0}if(a.constructor=== Object)return mc(a,b);throw Error("e");};
_.F=function(){this.K=this.K;this.C=this.C};_.F.prototype.K=!1;_.F.prototype.Z=function(){this.K||(this.K=!0,this.B())};_.I=function(a,b){_.G(a,_.xa(_.H,b))};_.G=function(a,b,c){a.K?_.m(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.r)(b,c):b))};_.F.prototype.B=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.Z&&a.Z()};
var nc=!_.x||9<=Number(Rb);!_.Cb&&!_.x||_.x&&9<=Number(Rb)||_.Cb&&_.Pb("1.9.1");_.x&&_.Pb("9");_.oc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.qc=function(){this.a="";this.c=_.pc;this.b=null};_.qc.prototype.Wa=!0;_.qc.prototype.La=function(){return this.b};_.qc.prototype.Xa=!0;_.qc.prototype.Va=function(){return this.a};_.pc={};_.rc=function(a,b){var c=new _.qc;c.a=a;c.b=b;return c};_.rc("<!DOCTYPE html>",0);_.rc("",0);_.sc=_.rc("<br>",0);
var yc,Bc,Ac;_.vc=function(a){return a?new _.tc(_.uc(a)):Ga||(Ga=new _.tc)};_.xc=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.wc(window.document,"*",a,b)[0];return d||null};
_.wc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.eb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.zc=function(a,b){_.mb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:yc.hasOwnProperty(d)?a.setAttribute(yc[d],b):_.Ha(d,"aria-")||_.Ha(d,"data-")?a.setAttribute(d,b):a[d]=b})};yc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
Bc=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.Ba(f)||_.ya(f)&&0<f.nodeType?d(f):(0,_.u)(Ac(f)?_.ib(f):f,d)}};_.Cc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.uc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};Ac=function(a){if(a&&"number"==typeof a.length){if(_.ya(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.za(a))return"function"==typeof a.item}return!1};
_.tc=function(a){this.a=a||_.l.document||window.document};_.g=_.tc.prototype;_.g.ya=_.vc;_.g.F=function(a){return _.t(a)?this.a.getElementById(a):a};
_.g.na=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!nc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Sa(h.name),'"');if(h.type){f.push(' type="',_.Sa(h.type),'"');var k={};_.sb(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.t(h)?f.className=h:_.Ca(h)?f.className=h.join(" "):_.zc(f,h));2<e.length&&Bc(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
_.Dc=function(a){return function(){return a}}(!1);var Ec="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},Fc=function(){};Fc.prototype.next=function(){throw Ec;};Fc.prototype.ia=function(){return this};
var Gc=function(a){if(a instanceof Fc)return a;if("function"==typeof a.ia)return a.ia(!1);if(_.Ba(a)){var b=0,c=new Fc;c.next=function(){for(;;){if(b>=a.length)throw Ec;if(b in a)return a[b++];b++}};return c}throw Error("f");},Hc=function(a,b){if(_.Ba(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==Ec)throw c;}else{a=Gc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==Ec)throw c;}}},Ic=function(a){if(_.Ba(a))return _.ib(a);a=Gc(a);var b=[];Hc(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.J?(c=a.X(),d=a.V()):(c=pb(a),d=ob(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.J.prototype.V=function(){Jc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.X=function(){Jc(this);return this.a.concat()};_.Lc=function(a,b){return Kc(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.g=this.c=this.a.length=0};_.J.prototype.remove=function(a){return Kc(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&Jc(this),!0):!1};var Jc=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Kc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Kc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return Kc(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){Kc(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ia=function(a){Jc(this);var b=0,c=this.g,d=this,e=new Fc;e.next=function(){if(c!=d.g)throw Error("g");if(b>=d.a.length)throw Ec;var e=d.a[b++];return a?e:d.b[e]};return e};var Kc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Nc;_.Mc=function(a){if(a.V&&"function"==typeof a.V)return a.V();if(_.t(a))return a.split("");if(_.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ob(a)};
Nc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.Ba(a)||_.t(a))(0,_.u)(a,b,void 0);else{var c;if(a.X&&"function"==typeof a.X)c=a.X();else if(a.V&&"function"==typeof a.V)c=void 0;else if(_.Ba(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=pb(a);for(var d=_.Mc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Oc=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};Oc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Pc=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var Tc;_.Qc=[];_.Rc=[];_.Sc=!1;Tc=function(a){_.Qc[_.Qc.length]=a;if(_.Sc)for(var b=0;b<_.Rc.length;b++)a((0,_.r)(_.Rc[b].b,_.Rc[b]))};var Uc,Wc,Xc,Vc;Uc=function(a){_.l.setTimeout(function(){throw a;},0)};_.Yc=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));c=Vc(c);!_.za(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.w("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Wc||(Wc=Xc()),Wc(c)):_.l.setImmediate(c)};
Xc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.w("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.w("Trident")&&!_.w("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.gb;c.gb=null;a()}};return function(a){d.next={gb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Vc=function(a){return a};Tc(function(a){Vc=a});
var Zc=function(){this.b=this.a=null},ad=new Oc(function(){return new $c},function(a){a.reset()},100);Zc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var $c=function(){this.next=this.b=this.a=null};$c.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};$c.prototype.reset=function(){this.next=this.b=this.a=null};
var bd,cd,dd,ed,gd;_.fd=function(a,b){bd||cd();dd||(bd(),dd=!0);var c=ed,d=ad.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d};cd=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);bd=function(){a.then(gd)}}else bd=function(){_.Yc(gd)}};dd=!1;ed=new Zc;gd=function(){for(var a;a=ed.remove();){try{a.a.call(a.b)}catch(b){Uc(b)}Pc(ad,a)}dd=!1};
var hd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},id=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ld,md,nd,td,xd,jd,Ad,wd,ud;_.kd=function(a,b){this.a=0;this.C=void 0;this.g=this.b=this.c=null;this.h=this.j=!1;if(a!=_.Da)try{var c=this;a.call(b,function(a){jd(c,2,a)},function(a){jd(c,3,a)})}catch(d){jd(this,3,d)}};ld=function(){this.next=this.context=this.b=this.g=this.a=null;this.c=!1};ld.prototype.reset=function(){this.context=this.b=this.g=this.a=null;this.c=!1};md=new Oc(function(){return new ld},function(a){a.reset()},100);nd=function(a,b,c){var d=md.get();d.g=a;d.b=b;d.context=c;return d};
_.od=function(a){if(a instanceof _.kd)return a;var b=new _.kd(_.Da);jd(b,2,a);return b};_.qd=function(){var a,b=new _.kd(function(b){a=b});return new pd(b,a)};_.kd.prototype.then=function(a,b,c){return _.rd(this,_.za(a)?a:null,_.za(b)?b:null,c)};hd(_.kd);_.kd.prototype.cancel=function(a){0==this.a&&_.fd(function(){var b=new sd(a);td(this,b)},this)};
td=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.c||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?td(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):ud(c),vd(c,e,3,b)))}a.c=null}else jd(a,3,b)};xd=function(a,b){a.b||2!=a.a&&3!=a.a||wd(a);a.g?a.g.next=b:a.b=b;a.g=b};
_.rd=function(a,b,c,d){var e=nd(null,null,null);e.a=new _.kd(function(a,h){e.g=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof sd?h(b):a(e)}catch(q){h(q)}}:h});e.a.c=a;xd(a,e);return e.a};_.kd.prototype.v=function(a){this.a=0;jd(this,2,a)};_.kd.prototype.w=function(a){this.a=0;jd(this,3,a)};
jd=function(a,b,c){0==a.a&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.yd(c,a.v,a.w,a)||(a.C=c,a.a=b,a.c=null,wd(a),3!=b||c instanceof sd||zd(a,c)))};_.yd=function(a,b,c,d){if(a instanceof _.kd)return xd(a,nd(b||_.Da,c||null,d)),!0;if(id(a))return a.then(b,c,d),!0;if(_.ya(a))try{var e=a.then;if(_.za(e))return Ad(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
Ad=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};wd=function(a){a.j||(a.j=!0,_.fd(a.l,a))};ud=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};_.kd.prototype.l=function(){for(var a;a=ud(this);)vd(this,a,this.a,this.C);this.j=!1};
var vd=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,Bd(b,c,d);else try{b.c?b.g.call(b.context):Bd(b,c,d)}catch(e){Cd.call(null,e)}Pc(md,b)},Bd=function(a,b,c){2==b?a.g.call(a.context,c):a.b&&a.b.call(a.context,c)},zd=function(a,b){a.h=!0;_.fd(function(){a.h&&Cd.call(null,b)})},Cd=Uc,sd=function(a){_.Fa.call(this,a)};_.p(sd,_.Fa);sd.prototype.name="cancel";var pd=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Dd=function(a,b){this.l=[];this.L=a;this.A=b||null;this.j=this.c=!1;this.g=void 0;this.G=this.M=this.w=!1;this.v=0;this.a=null;this.C=0};_.Dd.prototype.cancel=function(a){if(this.c)this.g instanceof _.Dd&&this.g.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.L?this.L.call(this.A,this):this.G=!0;this.c||this.H(new _.Ed)}};_.Dd.prototype.I=function(a,b){this.w=!1;Fd(this,a,b)};
var Fd=function(a,b,c){a.c=!0;a.g=c;a.j=!b;Gd(a)},Id=function(a){if(a.c){if(!a.G)throw new Hd;a.G=!1}};_.Dd.prototype.b=function(a){Id(this);Fd(this,!0,a)};_.Dd.prototype.H=function(a){Id(this);Fd(this,!1,a)};_.Kd=function(a,b,c){_.Jd(a,b,null,c)};_.Jd=function(a,b,c,d){a.l.push([b,c,d]);a.c&&Gd(a)};_.Dd.prototype.then=function(a,b,c){var d,e,f=new _.kd(function(a,b){d=a;e=b});_.Jd(this,d,function(a){a instanceof _.Ed?f.cancel():e(a)});return f.then(a,b,c)};hd(_.Dd);
_.Ld=function(a,b){b instanceof _.Dd?_.Kd(a,(0,_.r)(b.h,b)):_.Kd(a,function(){return b})};_.Dd.prototype.h=function(a){var b=new _.Dd;_.Jd(this,b.b,b.H,b);a&&(b.a=this,this.C++);return b};
var Md=function(a){return(0,_.bb)(a.l,function(a){return _.za(a[1])})},Gd=function(a){if(a.v&&a.c&&Md(a)){var b=a.v,c=Nd[b];c&&(_.l.clearTimeout(c.a),delete Nd[b]);a.v=0}a.a&&(a.a.C--,delete a.a);for(var b=a.g,d=c=!1;a.l.length&&!a.w;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var k=f.call(e||a.A,b);_.m(k)&&(a.j=a.j&&(k==b||k instanceof Error),a.g=b=k);if(id(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.w=!0}catch(n){b=n,a.j=!0,Md(a)||(c=!0)}}a.g=b;d&&(k=(0,_.r)(a.I,
a,!0),d=(0,_.r)(a.I,a,!1),b instanceof _.Dd?(_.Jd(b,k,d),b.M=!0):b.then(k,d));c&&(b=new Od(b),Nd[b.a]=b,a.v=b.a)},Hd=function(){_.Fa.call(this)};_.p(Hd,_.Fa);Hd.prototype.message="Deferred has already fired";Hd.prototype.name="AlreadyCalledError";_.Ed=function(){_.Fa.call(this)};_.p(_.Ed,_.Fa);_.Ed.prototype.message="Deferred was canceled";_.Ed.prototype.name="CanceledError";var Od=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a}; Od.prototype.c=function(){delete Nd[this.a];throw this.b;};var Nd={};
var Pd=!_.x||9<=Number(Rb),Qd=_.x&&!_.Pb("9");!_.Db||_.Pb("528");_.Cb&&_.Pb("1.9b")||_.x&&_.Pb("8")||Ab&&_.Pb("9.5")||_.Db&&_.Pb("528");_.Cb&&!_.Pb("8")||_.x&&_.Pb("9");_.K=function(a,b){this.type="undefined"!=typeof _.Rd&&a instanceof _.Rd?String(a):a;this.b=this.target=b;this.g=!1;this.lb=!0};_.K.prototype.l=function(){this.g=!0};_.K.prototype.c=function(){this.lb=!1};var Sd=function(a,b){_.K.call(this,a?a.type:"");this.b=this.target=null;this.keyCode=0;this.C=this.v=this.h=this.j=!1;this.a=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Cb&&_.yb(c,"nodeName");this.keyCode=a.keyCode||0;this.j=a.ctrlKey;this.h=a.altKey;this.v=a.shiftKey;this.C=a.metaKey;this.state=a.state;this.a=a;a.defaultPrevented&&this.c()}};_.p(Sd,_.K);
Sd.prototype.l=function(){Sd.D.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Sd.prototype.c=function(){Sd.D.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Qd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Td="closure_listenable_"+(1E6*Math.random()|0),Ud=function(a){return!(!a||!a[Td])},Vd=0;var Wd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.wa=!!d;this.Na=e;this.key=++Vd;this.removed=this.Ja=!1},Xd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Na=null};var Yd=function(a){this.src=a;this.a={};this.b=0},$d=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var k=Zd(b,c,e,f);-1<k?(a=b[k],d||(a.Ja=!1)):(a=new Wd(c,a.src,h,!!e,f),a.Ja=d,b.push(a));return a};Yd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Zd(e,b,c,d);return-1<b?(Xd(e[b]),_.fb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ae=function(a,b){var c=b.type;c in a.a&&_.gb(a.a[c],b)&&(Xd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Yd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Xd(d[e]);delete this.a[c];this.b--}return b};
var be=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Zd(a,c,d,e));return-1<b?a[b]:null},ce=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return nb(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].wa))return!0;return!1})},Zd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.wa==!!c&&f.Na==d)return e}return-1};
var de,ee,fe,ie,ke,pe,le,re,qe,me,je,se,he;de="closure_lm_"+(1E6*Math.random()|0);ee={};fe=0;_.ge=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.ge(a,b[f],c,d,e);return null}c=he(c);return Ud(a)?a.listen(b,c,d,e):ie(a,b,c,!1,d,e)};
ie=function(a,b,c,d,e,f){if(!b)throw Error("h");var h=!!e,k=je(a);k||(a[de]=k=new Yd(a));c=$d(k,b,c,d,e,f);if(c.proxy)return c;d=ke();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(le(b.toString()),d);else throw Error("i");fe++;return c};ke=function(){var a=me,b=Pd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.ne=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.ne(a,b[f],c,d,e);return null}c=he(c);return Ud(a)?a.Ma(b,c,d,e):ie(a,b,c,!0,d,e)};_.oe=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)_.oe(a,b[f],c,d,e);else c=he(c),Ud(a)?a.ta(b,c,d,e):a&&(a=je(a))&&(b=be(a,b,c,!!d,e))&&pe(b)};
pe=function(a){if(_.Aa(a)||!a||a.removed)return;var b=a.src;if(Ud(b)){ae(b.c,a);return}var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.wa):b.detachEvent&&b.detachEvent(le(c),d);fe--;(c=je(b))?(ae(c,a),0==c.b&&(c.src=null,b[de]=null)):Xd(a)};le=function(a){return a in ee?ee[a]:ee[a]="on"+a};re=function(a,b,c,d){var e=!0;if(a=je(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.wa==c&&!f.removed&&(f=qe(f,d),e=e&&!1!==f)}return e};
qe=function(a,b){var c=a.listener,d=a.Na||a.src;a.Ja&&pe(a);return c.call(d,b)};
me=function(a,b){if(a.removed)return!0;if(!Pd){var c=b||_.Ea("window.event"),d=new Sd(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.b;f;f=f.parentNode)c.push(f);for(var f=a.type,h=c.length-1;!d.g&&0<=h;h--){d.b=c[h];var k=re(c[h],f,!0,d),e=e&&k}for(h=0;!d.g&&h<c.length;h++)d.b=c[h],k=re(c[h],f,!1,d),e=e&&k}return e}return qe(a,new Sd(b,this))}; je=function(a){a=a[de];return a instanceof Yd?a:null};se="__closure_events_fn_"+(1E9*Math.random()>>>0);he=function(a){if(_.za(a))return a;a[se]||(a[se]=function(b){return a.handleEvent(b)});return a[se]};Tc(function(a){me=a(me)});
_.L=function(){_.F.call(this);this.c=new Yd(this);this.ga=this;this.G=null};_.p(_.L,_.F);_.L.prototype[Td]=!0;_.L.prototype.I=function(a){this.G=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.oe(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);var d=a.ga,e=b,f=e.type||e;if(_.t(e))e=new _.K(e,d);else if(e instanceof _.K)e.target=e.target||d;else{var h=e,e=new _.K(f,d);_.sb(e,h)}var h=!0,k;if(c)for(var n=c.length-1;!e.g&&0<=n;n--)k=e.b=c[n],h=k.pa(f,!0,e)&&h;e.g||(k=e.b=d,h=k.pa(f,!0,e)&&h,e.g||(h=k.pa(f,!1,e)&&h));if(c)for(n=0;!e.g&&n<c.length;n++)k=e.b=c[n],h=k.pa(f,!1,e)&&h;return h};_.g=_.L.prototype;
_.g.B=function(){_.L.D.B.call(this);this.c&&this.c.removeAll(void 0);this.G=null};_.g.listen=function(a,b,c,d){return $d(this.c,String(a),b,!1,c,d)};_.g.Ma=function(a,b,c,d){return $d(this.c,String(a),b,!0,c,d)};_.g.ta=function(a,b,c,d){return this.c.remove(String(a),b,c,d)}; _.g.pa=function(a,b,c){a=this.c.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.wa==b){var h=f.listener,k=f.Na||f.src;f.Ja&&ae(this.c,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.lb};
var te=function(){};te.prototype.a=null;var ve=function(a){var b;(b=a.a)||(b={},ue(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var we,xe=function(){};_.p(xe,te);var ye=function(a){return(a=ue(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},ue=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};we=new xe;
_.ze=function(a,b){_.L.call(this);this.h=a||1;this.g=b||_.l;this.j=(0,_.r)(this.v,this);this.l=(0,_.sa)()};_.p(_.ze,_.L);_.ze.prototype.b=!1;_.ze.prototype.a=null;_.ze.prototype.setInterval=function(a){this.h=a;this.a&&this.b?(this.stop(),_.Ae(this)):this.a&&this.stop()};
_.ze.prototype.v=function(){if(this.b){var a=(0,_.sa)()-this.l;0<a&&a<.8*this.h?this.a=this.g.setTimeout(this.j,this.h-a):(this.a&&(this.g.clearTimeout(this.a),this.a=null),_.M(this,"tick"),this.b&&(this.a=this.g.setTimeout(this.j,this.h),this.l=(0,_.sa)()))}};_.Ae=function(a){a.b=!0;a.a||(a.a=a.g.setTimeout(a.j,a.h),a.l=(0,_.sa)())};_.ze.prototype.stop=function(){this.b=!1;this.a&&(this.g.clearTimeout(this.a),this.a=null)};_.ze.prototype.B=function(){_.ze.D.B.call(this);this.stop();delete this.g}; _.Be=function(a,b,c){if(_.za(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.Ce=function(a){_.l.clearTimeout(a)};
var De=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Ee=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var Fe=function(a){_.L.call(this);this.headers=new _.J;this.H=a||null;this.b=!1;this.A=this.a=null;this.O="";this.j=0;this.h="";this.g=this.M=this.v=this.L=!1;this.l=0;this.w=null;this.aa="";this.T=this.W=!1},Ge,He,Qe,Oe,Me,Re,Se;_.p(Fe,_.L);Ge=/^https?$/i;He=["POST","PUT"];_.Ie=[];_.Je=function(a,b,c,d,e,f,h){var k=new Fe;_.Ie.push(k);b&&k.listen("complete",b);k.Ma("ready",k.ha);f&&(k.l=Math.max(0,f));h&&(k.W=h);k.send(a,c,d,e)};Fe.prototype.ha=function(){this.Z();_.gb(_.Ie,this)};
Fe.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.O+"`"+a);b=b?b.toUpperCase():"GET";this.O=a;this.h="";this.j=0;this.L=!1;this.b=!0;this.a=this.H?ye(this.H):ye(we);this.A=this.H?ve(this.H):ve(we);this.a.onreadystatechange=(0,_.r)(this.$,this);try{this.M=!0,this.a.open(b,String(a),!0),this.M=!1}catch(f){Ke(this,f);return}a=c||"";var e=new _.J(this.headers);d&&Nc(d,function(a,b){e.set(b,a)});d=_.db(e.X(),Le);c=_.l.FormData&&a instanceof _.l.FormData;!_.eb(He,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.aa&&(this.a.responseType=this.aa);"withCredentials"in this.a&&this.a.withCredentials!==this.W&&(this.a.withCredentials=this.W);try{Me(this),0<this.l&&((this.T=Ne(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.r)(this.Y,this)):this.w=_.Be(this.Y,this.l,this)),this.v=!0,this.a.send(a),this.v=!1}catch(f){Ke(this,f)}};
var Ne=function(a){return _.x&&_.Pb(9)&&_.Aa(a.timeout)&&_.m(a.ontimeout)},Le=function(a){return"content-type"==a.toLowerCase()};Fe.prototype.Y=function(){"undefined"!=typeof _.qa&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.M(this,"timeout"),this.a&&this.b&&(this.b=!1,this.g=!0,this.a.abort(),this.g=!1,this.j=8,_.M(this,"complete"),_.M(this,"abort"),Oe(this)))};
var Ke=function(a,b){a.b=!1;a.a&&(a.g=!0,a.a.abort(),a.g=!1);a.h=b;a.j=5;Pe(a);Oe(a)},Pe=function(a){a.L||(a.L=!0,_.M(a,"complete"),_.M(a,"error"))};Fe.prototype.B=function(){this.a&&(this.b&&(this.b=!1,this.g=!0,this.a.abort(),this.g=!1),Oe(this,!0));Fe.D.B.call(this)};Fe.prototype.$=function(){this.K||(this.M||this.v||this.g?Qe(this):this.P())};Fe.prototype.P=function(){Qe(this)};
Qe=function(a){if(a.b&&"undefined"!=typeof _.qa&&(!a.A[1]||4!=Re(a)||2!=Se(a)))if(a.v&&4==Re(a))_.Be(a.$,0,a);else if(_.M(a,"readystatechange"),4==Re(a)){a.b=!1;try{if(_.Te(a))_.M(a,"complete"),_.M(a,"success");else{a.j=6;var b;try{b=2<Re(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Se(a)+"]";Pe(a)}}finally{Oe(a)}}};Oe=function(a,b){if(a.a){Me(a);var c=a.a,d=a.A[0]?_.Da:null;a.a=null;a.A=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
Me=function(a){a.a&&a.T&&(a.a.ontimeout=null);_.Aa(a.w)&&(_.Ce(a.w),a.w=null)};_.Te=function(a){var b=Se(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.O).match(De)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ge.test(a?a.toLowerCase():"");c=b}return c};Re=function(a){return a.a?a.a.readyState:0};Se=function(a){try{return 2<Re(a)?a.a.status:-1}catch(b){return-1}}; _.Ue=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Tc(function(a){Fe.prototype.P=a(Fe.prototype.P)});
var Ye;_.N=function(a){_.F.call(this);this.v=a;this.g={}};_.p(_.N,_.F);var Ve=[];_.N.prototype.listen=function(a,b,c,d){_.Ca(b)||(b&&(Ve[0]=b.toString()),b=Ve);for(var e=0;e<b.length;e++){var f=_.ge(a,b[e],c||this.handleEvent,d||!1,this.v||this);if(!f)break;this.g[f.key]=f}return this};_.Ze=function(a,b,c,d){Ye(a,b,c,d,void 0)};Ye=function(a,b,c,d,e,f){if(_.Ca(c))for(var h=0;h<c.length;h++)Ye(a,b,c[h],d,e,f);else{b=_.ne(b,c,d||a.handleEvent,e,f||a.v||a);if(!b)return;a.g[b.key]=b}};
_.N.prototype.ta=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)this.ta(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.v||this,c=he(c),d=!!d,b=Ud(a)?be(a.c,String(b),c,d,e):a?(a=je(a))?be(a,b,c,d,e):null:null,b&&(pe(b),delete this.g[b.key]);return this};_.N.prototype.removeAll=function(){_.mb(this.g,function(a,b){this.g.hasOwnProperty(b)&&pe(a)},this);this.g={}};_.N.prototype.B=function(){_.N.D.B.call(this);this.removeAll()};_.N.prototype.handleEvent=function(){throw Error("m");};
var $e=function(){};$e.prototype.g=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var af=function(a){(a?a:function(){}).Ib=!0};_.bf=function(){};_.p(_.bf,$e);_.bf.prototype.b=function(a){return a};af(_.bf.prototype.b);_.bf.prototype.c=function(){return!0};af(_.bf.prototype.c);var cf=function(a){_.z(this,a,0,null)};_.p(cf,_.y);var df;df=function(a,b){var c=new cf;_.B(c,1,b);_.B(c,2,a);return c};_.ef=df("?",0);_.ff=df("q",1);_.gf=df("<",2);_.hf=df(">",3);_.jf=df("~",4);_.kf=df("s",5);_.O=function(a,b,c){this.c=a;this.b=b||null;this.a=c||[]};_.O.prototype.toString=function(){return this.c};var lf,mf,of,qf,rf,Af,sf,uf,tf,xf,vf,nf,Bf;
_.P=function(a,b){this.b=this.C=this.h="";this.g=null;this.l=this.a="";this.j=!1;var c;if(a instanceof _.P){this.j=_.m(b)?b:a.j;lf(this,a.h);this.C=a.C;this.b=a.b;mf(this,a.g);this.a=a.a;c=a.c;var d=new nf;d.c=c.c;c.a&&(d.a=new _.J(c.a),d.b=c.b);of(this,d);_.pf(this,a.l)}else a&&(c=String(a).match(De))?(this.j=!!b,lf(this,c[1]||"",!0),this.C=qf(c[2]||""),this.b=qf(c[3]||"",!0),mf(this,c[4]),this.a=qf(c[5]||"",!0),of(this,c[6]||"",!0),_.pf(this,c[7]||"",!0)):(this.j=!!b,this.c=new nf(null,0,this.j))};
_.P.prototype.toString=function(){var a=[],b=this.h;b&&a.push(rf(b,sf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(rf(b,sf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.g,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(rf(c,"/"==c.charAt(0)?tf:uf,!0));(c=this.c.toString())&&a.push("?",c);(c=this.l)&&a.push("#",rf(c,vf));return a.join("")};
lf=function(a,b,c){a.h=c?qf(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};mf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("r`"+b);a.g=b}else a.g=null};of=function(a,b,c){b instanceof nf?(a.c=b,wf(a.c,a.j)):(c||(b=rf(b,xf)),a.c=new nf(b,0,a.j))};_.R=function(a,b,c){a.c.set(b,c)};_.pf=function(a,b,c){a.l=c?qf(b):b};_.yf=function(a){return a instanceof _.P?new _.P(a):new _.P(a,void 0)};
_.zf=function(a,b){a instanceof _.P||(a=_.yf(a));b instanceof _.P||(b=_.yf(b));var c=a,d=b,e=new _.P(c),f=!!d.h;f?lf(e,d.h):f=!!d.C;f?e.C=d.C:f=!!d.b;f?e.b=d.b:f=null!=d.g;var h=d.a;if(f)mf(e,d.g);else if(f=!!d.a)if("/"!=h.charAt(0)&&(c.b&&!c.a?h="/"+h:(c=e.a.lastIndexOf("/"),-1!=c&&(h=e.a.substr(0,c+1)+h))),c=h,".."==c||"."==c)h="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var h=_.Ha(c,"/"),c=c.split("/"),k=[],n=0;n<c.length;){var q=c[n++];"."==q?h&&n==c.length&&k.push(""):".."==q?((1<
k.length||1==k.length&&""!=k[0])&&k.pop(),h&&n==c.length&&k.push("")):(k.push(q),h=!0)}h=k.join("/")}else h=c;f?e.a=h:f=""!==d.c.toString();f?of(e,qf(d.c.toString())):f=!!d.l;f&&_.pf(e,d.l);return e};qf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};rf=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Af),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
Af=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};sf=/[#\/\?@]/g;uf=/[\#\?:]/g;tf=/[\#\?]/g;xf=/[\#\?@]/g;vf=/#/g;nf=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c};Bf=function(a){a.a||(a.a=new _.J,a.b=0,a.c&&Ee(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));Bf(a);a.c=null;var d=Cf(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b+=1}))};
nf.prototype.remove=function(a){Bf(this);a=Cf(this,a);return _.Lc(this.a,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};nf.prototype.clear=function(){this.a=this.c=null;this.b=0};var Df=function(a,b){Bf(a);b=Cf(a,b);return _.Lc(a.a,b)};nf.prototype.X=function(){Bf(this);for(var a=this.a.V(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
nf.prototype.V=function(a){Bf(this);var b=[];if(_.t(a))Df(this,a)&&(b=_.hb(b,this.a.get(Cf(this,a))));else{a=this.a.V();for(var c=0;c<a.length;c++)b=_.hb(b,a[c])}return b};nf.prototype.set=function(a,b){Bf(this);this.c=null;a=Cf(this,a);Df(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};nf.prototype.get=function(a,b){var c=a?this.V(a):[];return 0<c.length?String(c[0]):b};_.Ef=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(Cf(a,b),_.ib(c)),a.b+=c.length)};
nf.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.V(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.c=a.join("&")}; var Cf=function(a,b){var c=String(b);a.g&&(c=c.toLowerCase());return c},wf=function(a,b){b&&!a.g&&(Bf(a),a.c=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Ef(this,c,a))},a));a.g=b};
_.bf.D||_.p(_.bf,$e);_.Ff=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
_.Gf=function(a){_.z(this,a,"uv_qm",null)};_.p(_.Gf,_.y);_.Gf.messageId="uv_qm";_.Hf=function(a){_.z(this,a,"uv_r_rdm",null)};_.p(_.Hf,_.y);_.Hf.messageId="uv_r_rdm";_.If=function(a){_.z(this,a,"uv_r_rr",null)};_.p(_.If,_.y);_.If.messageId="uv_r_rr";_.Jf=function(a){_.z(this,a,"uv_r_frm",null)};_.p(_.Jf,_.y);_.Jf.messageId="uv_r_frm";_.Kf=function(a){_.z(this,a,0,null)};_.p(_.Kf,_.y);
var Mf=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("t");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,q,v,Y){if("%"==q)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("u");arguments[0]=e;return Lf[q].apply(null,arguments)})},Lf={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ta(" ",Number(c)-a.length):Ta(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ta(" ",a):f+Ta(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return Lf.f((0,window.parseInt)(a,10),b, c,d,0,f,h,k)}};Lf.i=Lf.d;Lf.u=Lf.d;
_.S=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Mf("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+Mf(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Mf.apply({},c)))};
_.Nf=new _.O("pVbxBc");_.T=new _.O("nED8Yb");_.Of=new _.O("xclgJb");_.Pf=new _.O("Qz9Lj");_.Rf=function(a){_.z(this,a,"h_exts",Qf)};_.p(_.Rf,_.y);var Qf=[2];_.Rf.messageId="h_exts";_.Sf=function(a){return _.zf(a,"/webchat/host-js")};_.Tf=function(a){var b=_.Sf(_.A(a,2));_.R(b,"prop",_.Ff(27));_.R(b,"b",1);_.R(b,"hl",_.A(a,3));_.A(a,4)&&_.R(b,"jsmode",_.A(a,4));_.R(b,"zx",_.Va());return b.toString()};var Uf;Uf=function(a){return(a=a.exec(_.jb))?a[1]:""};_.Vf=function(){if(Sb)return Uf(/Firefox\/([0-9.]+)/);if(_.x||Bb||Ab)return Nb;if(Wb)return Uf(/Chrome\/([0-9.]+)/);if(Xb&&!(ub()||_.w("iPad")||_.w("iPod")))return Uf(/Version\/([0-9.]+)/);if(Tb||Ub){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.jb);if(a)return a[1]+"."+a[2]}else if(Vb)return(a=Uf(/Android\s+([0-9.]+)/))?a:Uf(/Version\/([0-9.]+)/);return""}();
_.Wf=function(a,b){this.l=a||"e";this.g=null!=a&&"p"==a?"e":"p";this.c=this.h=null;this.j=b||"u";this.a=this.C=null;this.b=[]};_.Wf.prototype.message=function(){var a={};a.i=this.a;a.m=this.b;a.r=this.j;a.o=this.C;a.s=this.c;a.st=this.g;a.d=this.h;a.dt=this.l;return a};_.Wf.prototype.message=_.Wf.prototype.message;_.Wf.prototype.source=function(){return this.c};_.Wf.prototype.target=function(){return this.h};_.Wf.prototype.content=function(){return this.b};
var Xf=function(a,b){_.K.call(this,a,b);this.S=b};_.p(Xf,_.K);var Yf=function(a){_.z(this,a,"capi_md1571",null)};_.p(Yf,_.y);Yf.messageId="capi_md1571";var Zf={bb:0,tc:1,sc:2,ab:3,Qa:4},$f=function(a){_.z(this,a,0,null)};_.p($f,_.y);var bg=function(){for(var a=10,b=ag,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},ag="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.cg=function(a,b){_.F.call(this);this.j=b||bg();this.g=this.a="";this.b=this.c=null;this.l=a;this.h=new _.N(this);_.I(this,this.h);this.h.listen(window,"message",this.v)};_.p(_.cg,_.F);_.cg.prototype.da=function(a,b,c){this.g=a;this.c=b;this.b=c};
_.cg.prototype.v=function(a){a=a.a;var b;b=a.origin;this.c&&this.c!=a.source||"*"!=this.g&&this.g!=b?b=!1:this.b?(b=(new _.P(b)).b,b=_.Ia(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.t(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.Ca(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new Yf(c),_.A(c,1)==this.j)){b=_.A(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.g&&this.c||this.da(a.origin,a.source);
1==_.A(c,2)?this.send(2):this.l(c,a)}}};_.cg.prototype.send=function(a,b,c){if(this.a&&this.c){b=b||new Yf;_.B(b,3,this.j);_.B(b,1,this.a);_.B(b,2,a);var d=JSON.stringify(_.D(b)),e=this.c,f=this.g;_.x?_.Be(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var dg=function(a,b,c,d,e){this.c=_.qd();this.a=new _.cg((0,_.r)(this.h,this),d);this.a.da(a,b,e);this.a.a=c;this.b=new _.ze(50);_.Ae(this.b);_.ge(this.b,"tick",this.g,!1,this);this.g();a=this.c.a;b=this.j;b=nd(b,b,this);b.c=!0;xd(a,b)};dg.prototype.j=function(){_.H(this.a);_.oe(this.b,"tick",this.g,!1,this);_.H(this.b)};dg.prototype.g=function(){this.a.send(1)};dg.prototype.h=function(a,b){2==_.A(a,2)&&this.c.b(b.origin)};
var eg=function(a,b,c){_.F.call(this);this.b=a;a=_.A(b,3);b=_.A(b,1);this.a=new _.cg((0,_.r)(this.c,this),b);this.a.a=a;c&&this.a.da(c.origin,c.source);_.I(this,this.a)};_.p(eg,_.F);eg.prototype.send=function(a){var b=new Yf;_.E(b,4,a);this.a.send(Zf.bb,b)};eg.prototype.connect=function(a,b){this.a.da(a,b);this.a.send(Zf.ab)};eg.prototype.c=function(a){_.A(a,2)==Zf.bb&&(a=_.C(a,$f,4),this.b(a))};eg.prototype.g=_.Da;
var gg=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.c=null;c?(this.b=c.ports[0],fg(this)):(this.a=new _.cg(_.Da,_.A(b,1)),a=_.A(b,3),this.a.a=a)};_.p(gg,_.F);gg.prototype.B=function(){gg.D.B.call(this);this.b&&this.b.close();_.H(this.a)};gg.prototype.g=function(){this.c=new _.N(this);_.I(this,this.c);fg(this)};gg.prototype.send=function(a){this.b.postMessage(_.D(a))};
gg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;fg(this);var d=this.a;this.a=null;c=c.port2;d.da(a,b);d.send(Zf.Qa,void 0,[c]);_.H(d)};var fg=function(a){a.b&&a.c&&(a.c.listen(a.b,"message",a.j),a.b.start())};gg.prototype.j=function(a){a=a.a;var b;try{b=new $f(a.data)}catch(c){return}this.h(b)};
var hg=function(a,b,c){var d=!1;_.m(_.A(b,2))?_.A(b,2)==Zf.Qa&&(d=!0):d=Wb;return d?new gg(a,b,c):new eg(a,b,c)};var lg;_.ig=function(){_.L.call(this);this.h=null;this.l=!1;this.j=[];this.g=[];_.G(this,this.w,this);this.b=null};_.p(_.ig,_.L);_.ig.prototype.w=function(){for(;this.g.length;)this.g.shift()()};_.kg=function(a){a.w();a.j=[];a.b=new _.Dd;a.g.push((0,_.r)(a.b.cancel,a.b));a.l=!1;_.Kd(a.b.h(),function(a){(ce(this.c)||this.G)&&jg(this);this.g.push(_.xa(_.H,a))},a)};_.g=_.ig.prototype;_.g.sendMessage=function(a){this.xa(_.D(a))};_.g.xa=function(a){if(this.b){var b=new $f;_.B(b,1,a);_.Kd(this.b.h(),function(a){a.send(b)})}};
_.g.$a=function(a){this.h=a;_.G(this,function(){this.h=null},this);jg(this)};_.g.J=function(){return this};_.g.da=function(a,b,c){this.a.da(a,b,c)};_.mg=function(a,b,c,d){_.kg(a);lg(a,b,c,d).then(function(a){var d=new Yf;_.B(d,1,a.pc);_.B(d,3,c);d=hg((0,_.r)(this.v,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};lg=function(a,b,c,d){var e=bg();b=(new dg("*",b,c,e,d)).c.a;a.g.push((0,_.r)(b.cancel,b));return b.then(function(a){return{pc:e,origin:a}})};
_.ig.prototype.H=function(a,b){if(_.A(a,2)==Zf.ab||_.A(a,2)==Zf.Qa)_.H(this.a),this.a=null,this.b.b(hg((0,_.r)(this.v,this),a,b))};_.ig.prototype.v=function(a){this.j.push(a);this.A()};_.ig.prototype.A=function(){for(;ng(this););};var ng=function(a){if(a.K||!a.l||0==a.j.length)return!1;var b=_.A(a.j.shift(),1);a.h&&a.h.xa(b);_.M(a,new Xf(b[0],b));return!0},jg=function(a){a.l||(a.l=!0,a.b&&_.Kd(a.b.h(),function(a){a.g();_.Be(this.A,0,this)},a))}; _.ig.prototype.listen=function(a,b,c,d){jg(this);return _.ig.D.listen.call(this,a,b,c,d)};_.ig.prototype.Ma=function(a,b,c,d){jg(this);return _.ig.D.Ma.call(this,a,b,c,d)};_.ig.prototype.I=function(a){jg(this);return _.ig.D.I.call(this,a)};
var og=function(a){this.b=a;this.g="empty";this.a=null;this.c={}};og.prototype.setVersion=function(a){this.g=a;return this};og.prototype.Oa=function(a){this.a=a;return this};og.prototype.Za=function(a){this.c=_.qb(a);return this};var pg=function(){};var qg=function(){};_.p(qg,pg);qg.prototype.clear=function(){var a=Ic(this.ia(!0)),b=this;(0,_.u)(a,function(a){b.remove(a)})};var rg=function(a){this.a=a};_.p(rg,qg);_.g=rg.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ia=function(a){var b=0,c=this.a,d=new Fc;d.next=function(){if(b>=c.length)throw Ec;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var sg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.p(sg,rg);var ug=function(a,b){this.c=a;this.a=[];this.b=null;b&&(this.b=new sg);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=$b(c)||[]}catch(d){}}c=!1;_.Ca(this.a)||(this.a=[],c=!0);for(;this.a.length>this.c;)this.a.shift(),c=!0;c&&tg(this)},tg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.cc(a.a))}catch(b){}};
var vg=function(a){_.F.call(this);this.a=a;this.h=!1};_.p(vg,_.F);vg.prototype.setEnabled=function(a){this.h=a};var U=function(a){vg.call(this,a);this.w=100;this.v={};this.R=null;this.c="";this.G=!0;this.j=10;this.b=null;this.g=!1};_.p(U,vg);U.prototype.pb=function(a){this.G=a;return this};U.prototype.setUseLocalStorage=U.prototype.pb;U.prototype.oc=function(a){this.j=Math.min(a,100);return this};U.prototype.setMaxErrorsPerHour=U.prototype.oc;U.prototype.nb=function(a){this.w=a;return this};U.prototype.setGlobalSampling=U.prototype.nb;U.prototype.eb=function(a,b){this.v[a]=b;return this};
U.prototype.addPerErrorMessageSampling=U.prototype.eb;U.prototype.mb=function(a){this.R=a;return this};U.prototype.setCallback=U.prototype.mb;U.prototype.nc=function(a){this.c=a;return this};U.prototype.setClientId=U.prototype.nc;U.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.A.bind(this);this.setEnabled(!0);return!0};U.prototype.enable=U.prototype.enable;
U.prototype.jb=function(a,b,c,d,e){var f=_.yf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=(!_.za(this.R)||this.R(f.a,a,b,c,d,e))&&this.g){h=Object.keys(this.v);for(var k=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(k=this.v[q])}h=(100*Math.random()).toFixed(6)>=this.w*k/100?!1:!0}if(h){0<=this.j&&null===this.b&&(this.b=new ug(this.j,this.G));if(null===this.b)h=0;else{a:{h=this.b;k=(0,_.sa)();if(h.a.length==h.c)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
tg(h);h=!0}h=!h}h=!h}h&&this.g&&(h=_.qb(this.a.c),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",Ab?k="Opera":_.x?k="Internet Explorer":Sb?k="Firefox":Wb?k="Chrome":Xb&&(k="Safari"),h.browser=k,h.browser_version=_.Vf,h.os=_.w("CrOS")?"Chrome OS":_.w("Linux")?"Linux":_.wb()?"Windows":_.w("Android")?"Android":ub()?"iPhone":_.w("iPad")?"iPad":_.w("iPod")?"iPod":_.vb()?"Mac":"Unknown",k=_.jb,n="",_.wb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):ub()||_.w("iPad")||
_.w("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.vb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.w("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.w("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ja(this.c)||(h.guid=this.c),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.g,b=
wg(h),e=null!=e?_.Ua(e.stack):"",_.Ja(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),xg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ua(this.a.a),_.Ja(a)||(f.version=a),xg(this,"https://clients2.google.com/cr/staging_perf",wg(f)))};U.prototype.reportError=U.prototype.jb;U.prototype.A=function(a,b,c,d,e){this.jb(a,b,c,d,e);null!=this.l&&_.za(this.l)&&this.l(a,b,c,d,e)};
var wg=function(a){var b="",c;for(c in a)b+=_.Ja(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},xg=function(a,b,c,d){d=d||"";var e=_.Ja(d)?{}:{"Content-Type":"text/plain"};_.Je(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};U.prototype.I=function(a,b){_.Te(b.target)};
var yg=function(a){vg.call(this,a);this.R=null;this.b=0};_.p(yg,vg);yg.prototype.mb=function(a){this.R=a;return this};var zg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];yg.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.ze(6E4);_.I(this,a);var b=new _.N(this);_.I(this,b);b.listen(a,"tick",this.c);_.Ae(a);this.setEnabled(!0);return!0}return!1};
yg.prototype.c=function(){this.b+=6E4;for(var a="",b=0;b<zg.length;++b)if(this.b==zg[b].age){a=zg[b].name;break}if(""!=a){var b=Ag.test(_.jb)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.yf(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.Ua(this.a.a);_.Ja(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.za(this.R)&&this.R(b,a[d].displayName,a[d].value);_.Je("https://clients2.google.com/cr/staging_perf"+c,Bg,"POST","",null,6E4,!0)}}};var Bg=function(a){_.Te(a.target)},Ag=/(x86_64|Win64)/;
var Cg=function(a){_.F.call(this);this.b=new og(a);this.a={}};_.p(Cg,_.F);_.wa("webmonitoring.Monitoring",Cg);Cg.prototype.setVersion=function(a){this.b.setVersion(a);return this};Cg.prototype.setVersion=Cg.prototype.setVersion;Cg.prototype.Oa=function(a){this.b.Oa(a);return this};Cg.prototype.setChannel=Cg.prototype.Oa;Cg.prototype.Za=function(a){this.b.Za(a);return this};Cg.prototype.setContext=Cg.prototype.Za;Cg.prototype.Ka=function(){null!=this.a[2]||(this.a[2]=new U(this.b));return this.a[2]}; Cg.prototype.createJsErrorsReporter=Cg.prototype.Ka;
var Dg=function(a){Cg.call(this,a)};_.p(Dg,Cg);Dg.prototype.Ka=function(){var a=Dg.D.Ka.call(this);a.g=!0;return a};_.Eg=function(){var a=new Dg("Google_Hangouts_Chrome");a.Oa(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new yg(a.b));a.a[1].enable();a.Ka().pb(!1).nb(100).eb("Script error.",0).enable()};var Fg=function(a,b){this.c=a;this.b=b;this.constructor.fb||(this.constructor.fb={});this.constructor.fb[this.toString()]=this};Fg.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var Gg=function(a,b){Fg.call(this,a,b)};_.p(Gg,Fg);var Hg=function(a){this.a=a};new Hg("lib");var Ig,Qg,Rg,Sg;_.Jg=function(a){_.F.call(this);this.g={};this.j={};this.l={};this.a={};this.c={};this.I={};this.v=a?a.J():new _.L;this.P=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.c=a.c):(0,_.sa)();a=Ig(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Jg,_.F);_.Kg=.05>Math.random();Ig=function(a){for(;a.b;)a=a.b;return a};_.Jg.prototype.get=function(a){var b=_.Lg(this,a);if(null==b)throw new Mg(a);return b};
_.Lg=function(a,b){for(var c=a;c;c=c.b){if(c.K)throw Error("v");if(c.g[b])return c.g[b][0];if(c.I[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("w`"+b);_.Ng(a,b,c);return c}return null};
_.Jg.prototype.G=function(a,b){var c=_.Lg(this,a);if(null==c){if(this.c[a]){var d=this.c[a].h();_.Kd(d,(0,_.r)(this.G,this,a,b));return d}throw new Og(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.Ta?(d=new _.Dd,_.Ld(d,c.Ta()),d.b(c),_.Kd(d,(0,_.r)(this.w,this,a)),d):this.w(a)};_.Jg.prototype.w=function(a){this.c[a]&&delete this.c[a];return this.get(a)};_.Jg.prototype.L=function(a,b,c){return c instanceof _.Ed?c:new Pg(a,b,c)};
_.Ng=function(a,b,c,d){if(a.K)d||_.H(c);else{a.g[b]=[c,!d];d=Qg(a,a,b);for(var e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};Qg=function(a,b,c){var d=[],e=a.a[c];e&&(_.Za(e,function(a){var c;a:{for(c=a.Sa;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.gb(e,a))}),0==e.length&&delete a.a[c]);return d};Rg=function(a,b){a.a&&Nc(a.a,function(a,d,e){_.Za(a,function(c){c.Sa==b&&_.gb(a,c)});0==a.length&&delete e[d]})};
_.Jg.prototype.H=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].Sa==this&&c[d].d==b){_.fb(c,d);break}0==c.length&&delete this.a[a]}};_.Jg.prototype.B=function(){if(Ig(this)==this){var a=this.h;if(a)for(;a.length;)a[0].Z()}else for(var a=Ig(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.g)a=this.g[c],a[1]&&a[0].Z&&a[0].Z();this.g=null;this.P&&this.v.Z();Rg(this,this);this.a=null;_.H(this.O);this.I=this.O=null;_.Jg.D.B.call(this)};
_.Jg.prototype.J=function(){return this.v};var Mg=function(a){_.Fa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.p(Mg,_.Fa);var Pg=function(a,b,c){_.Fa.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.p(Pg,_.Fa);var Og=function(a,b,c){_.Fa.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.p(Og,_.Fa); Sg=new Hg("fva");_.Tg=new Gg(Sg,1);

}catch(e){_._DumpException(e)}
try{
var yp=/\s*;\s*/,zp=function(){return[]},Ap=function(a){a=(a.a.cookie||"").split(yp);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}},Bp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.ba[c[0]].prototype[a].apply(this,arguments)}:b[a].Kb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];if(f=f?f[a].apply(f,d):this.ba[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Jb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]],f=f?f[a].apply(f,d):this.ba[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].$b?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.ba[c[e]].prototype[a].apply(this,d)}}:
e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var q=this.a[c[f]];e.push(q?q[a].apply(q,d):this.ba[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Kb||b[a].Jb||b[a].$b?e=null:e=zp;return e},Cp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},Dp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ba(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},
Ep=[1],Fp=function(a,b){return a.c.get(b)},Gp=function(a){this.a=a||{cookie:""}};_.g=Gp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("p`"+a);if(/[;\r\n]/.test(b))throw Error("q`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.sa)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(yp),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.g.X=function(){return Ap(this).keys};_.g.V=function(){return Ap(this).values};_.g.clear=function(){for(var a=Ap(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Hp=function(a){return this.Ua.g(a)},Ip=function(a){_.z(this,a,"ci:ec",null)};
_.p(Ip,_.y);Ip.messageId="ci:ec";
var Jp={a:_.ef,G:_.ff,v:_.gf,w:_.hf,C:_.jf,I:_.kf},Kp=function(a){var b=a.oa,c=function(a){c.D.constructor.call(this,a);var b=this.ba.length;this.a=[];for(var d=0;d<b;++d)this.ba[d].Cc||(this.a[d]=new this.ba[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.oa){b.ba&&Dp(d,b.ba);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.za(e[f])&&e[f]!==b){var h=!!e[f].Ib,k=Cp(f,e,d,h);(h=Bp(f,e,k,h))&&(c.prototype[f]=h)}}a=a.D&&a.D.constructor}c.prototype.ba=d;return c},Lp=function(a){_.z(this,a,"capi:r_rstr",
null)};_.p(Lp,_.y);Lp.messageId="capi:r_rstr";var Mp=function(a){_.z(this,a,"capi:r_recl",null)};_.p(Mp,_.y);Mp.messageId="capi:r_recl";var Np=function(a){_.z(this,a,"capi:r_clre",null)};_.p(Np,_.y);Np.messageId="capi:r_clre";
var Op=function(a,b){var c={};try{c=JSON.parse(b)||{}}catch(e){}for(var d in c)switch(d){case "r":a.j=c[d];break;case "i":a.a=c[d];break;case "m":a.b=c[d];break;case "o":a.C=c[d];break;case "s":a.c=c[d];break;case "d":a.h=c[d];break;case "st":a.g=c[d];break;case "dt":a.l=c[d]}},Pp=function(a){_.z(this,a,0,Ep)};_.p(Pp,_.y);var Qp=function(a){_.z(this,a,"uv_r_hrd",null)};_.p(Qp,_.y);Qp.messageId="uv_r_hrd";var Rp=function(a){_.z(this,a,"uv_r_rrr",null)};_.p(Rp,_.y);Rp.messageId="uv_r_rrr";
var Sp=function(a){_.z(this,a,"uv_r_rdr",null)};_.p(Sp,_.y);Sp.messageId="uv_r_rdr";
var Tp=function(a,b,c){if(!this.Ua){for(var d=this.constructor;d&&!d.oa;)d=d.D&&d.D.constructor;d.oa.hb||(d.oa.hb=Kp(d));this.Ua=new d.oa.hb(this);this.g||(this.g=Hp)}var e=this.Ua.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ha(e,"https://talkgadget.google.com/talkgadget/")){var d=(new Gp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.eb(f,d)&&h.test(d)&&(e=_.yf(e),
e=_.yf("https://"+d+e.a).toString())}this.ma=e;this.c=c||new Ip;a.notificationsOnly&&_.B(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=Fp(new _.P(window.location.href),"authuser"),null!=c&&(this.b=c));this.v=a.clientUrl||"notifierclient";c=Fp(_.yf(this.v),"authuser");null!=c&&(this.b=c);this.Ra=a.propertyName||"Google Talk";this.G=a.cssUrl;this.locale=a.locale;this.C=a.debug;this.Ca=a.userJid;this.Ga=a.uiVersion;this.Ub=null!=a.rosterExpanded?a.rosterExpanded:!0;this.Y=a.hostLogMinValue;
this.Da=a.hideChat;this.Nb=a.refresh;this.O=a.hideProfileCard;this.W=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.P=a.hideRecentConversations;this.M=a.hideOTR;this.Hb=a.hostServerMessageCallback||!1;this.aa=a.isCentralRoster;this.Mb=a.isFullFrame||!1;this.Tb=a.rosterClass||"talk_roster";this.Vb=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.va=a.parentToken;
this.Rb=b||!1;this.j=_.m(a.isRtl)?a.isRtl:_.oc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in Jp)b.push(_.D(Jp[k]))}this.A=a.entityId;this.Ha=a.useQuasarPanels||!1;this.Ea=a.silent||!1;this.Lb=a.ignoreCentralRoster||!1;this.Qb=a.lazy||!1;this.Gb=a.handleProfileLinks||!1;this.$=a.hostSettings;this.l=a.screen;this.I=a.docsConfig;this.Ob=a.jsmode;this.ua=a.moleWidth;this.ha=a.moleHeight;this.ga=a.minimizedMoleHeight||36;this.Wb=a.derp;this.Fa=window.location.protocol+
"//"+window.location.host;this.h="";this.L=a.optOutAllowed;this.H=a.legacyTalkSignedIn;this.Ia=a.useSpareMole;this.w=a.conversationId};Tp.oa=_.bf;var Up=function(a){_.z(this,a,0,null)};_.p(Up,_.y);var Vp=function(a){_.z(this,a,0,null)};_.p(Vp,_.y);var Wp=function(a){_.z(this,a,0,null)};_.p(Wp,_.y);var Xp=function(a){_.z(this,a,0,null)};_.p(Xp,_.y);var Yp=function(a){_.z(this,a,"h_cc",null)};_.p(Yp,_.y);Yp.messageId="h_cc";
var Zp=function(a,b){_.rd(a,null,b,void 0)},$p=function(a,b,c){a=_.A(a,b);return null==a?c:a},aq=function(a,b,c){_.yd(a,b,c,null)||_.fd(_.xa(b,a))},bq=function(a){return new _.kd(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,n;k<a.length;k++)n=a[k],aq(n,_.xa(f,k),h);else b(e)})};
var cq=function(a){this.a=a;_.x||(delete this.a.lpu,delete this.a.ppu)},dq=["cn","tp"],eq=function(a,b){var c;if(_.za(window.document.postMessage)||_.za(window.postMessage)||_.x&&window.postMessage)c=1;else if(_.Cb)c=2;else{var d;if(d=_.x){d=!1;try{c=window.opener,window.opener={},d=_.yb(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new cq(d)};_.wa("GTalk_IFrameChannelConfig.build",eq);
var fq=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.c=new _.N(this);_.I(this,this.c);var f=_.jb;d=new _.P(a.ma+a.v);$p(a.c,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.Ub),_.R(d,"ref",a.Nb));_.R(d,"client","sm");_.R(d,"prop",a.Ra);_.R(d,"nav","true");_.R(d,"fid",a.a);a.C&&_.R(d,"debug",a.C);_.R(d,"os",_.Fb);_.R(d,"stime",c);a.Da&&_.R(d,"hc",a.Da);for(c=0;c<dq.length;++c);b=_.cc(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.cc(_.D(a.c)));a.l&&_.R(d,"screen",a.l);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.va&&_.R(d,"pvt",a.va);a.Hb&&_.R(d,"hsmc","true");_.m(a.Y)&&_.R(d,"logl",a.Y);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.P(window.location.href);"false"==Fp(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Ob)&&_.R(d,"jsmode",f);(f=Fp(b,"cssmode"))&&_.R(d,"cssmode",f);(f=Fp(b,"convid"))&&_.R(d,"convid",f);if(f=b.c.V("convp"))_.Ca(f)||(f=[String(f)]),_.Ef(d.c,"convp",f);(f=Fp(b,"smexp"))&&_.R(d,"smexp",
f);f=b.c.V("mods");a.Qb&&f.push("lazy");e&&(f=_.hb(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.ma||0>a.ma.indexOf("/u/"))(e=Fp(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=Fp(b,"eid");_.Ja(_.Ua(e))||_.R(d,"eid",e);_.Ja(_.Ua(this.a.A))||_.R(d,"eid",this.a.A);null!=this.a.position&&_.R(d,"pos",this.a.position);_.m(a.Ga)&&_.R(d,"uiv",this.a.Ga);a.G&&_.R(d,"css",a.G);e=a.locale||Fp(b,"hl");null!=e&&_.R(d,"hl",e);_.m(a.Ca)&&_.R(d,"uj",a.Ca);null!=a.O&&_.R(d,"hpc",a.O);null!=
a.W&&_.R(d,"hsm",a.W);null!=a.T&&_.R(d,"hro",a.T);null!=a.P&&_.R(d,"hrc",a.P);null!=a.M&&_.R(d,"hotr",a.M);null!=a.aa&&_.R(d,"pop",a.aa);a.Rb&&_.R(d,"pal","1");null!=a.Ha&&_.R(d,"uqp",a.Ha);null!=a.L&&_.R(d,"gooa",a.L);null!=a.H&&_.R(d,"gltsi",a.H);null!=a.Ia&&_.R(d,"gusm",a.Ia);null!=a.Ea&&_.R(d,"sl",a.Ea);a.Lb&&_.R(d,"icr","1");a.Gb&&_.R(d,"hpl","1");a.$&&_.R(d,"hs",a.$);a.I&&_.R(d,"dc",_.cc(_.D(a.I)));null!=a.ua&&_.R(d,"molew",a.ua);null!=a.ha&&_.R(d,"moleh",a.ha);null!=a.ga&&_.R(d,"mmoleh",a.ga);
a.Wb&&_.R(d,"derp","1");a.h&&_.R(d,"fcho",a.h);null!=a.Fa&&_.R(d,"two",a.Fa);null!=a.w&&_.R(d,"convid",a.w);_.R(d,"host","1");_.R(d,"zx",_.Va());this.g=d.toString()};_.p(fq,_.F);
var gq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Tb,a.b.body.appendChild(e));a=(0,_.r)(function(){var a="";this.a.Mb||(a="height:400px");var b=this.b.createElement("iframe");_.zc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.xc("talk_loading_msg",e)||_.Cc(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.Ze(this.c,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});k.src=this.g.toString();c()},a);window.setTimeout(a,0)};
var hq=new _.O("q"),iq=new _.O("r");var jq=function(a){_.L.call(this);this.a=a.get(iq);a=new _.N(this);_.I(this,a);a.listen(this.a.J(),"uv_r_frm",this.b);a.listen(this.a.J(),"uv_r_rdm",this.g)};_.p(jq,_.L);jq.prototype.reload=function(a){var b=new _.If;_.B(b,1,a);this.a.sendMessage(b)};jq.prototype.b=function(a){a=new _.Jf(a.S);_.M(this,new kq(!!_.A(a,1)))};jq.prototype.g=function(a){a=new _.Hf(a.S);_.M(this,new lq(_.A(a,1)))};var kq=function(a){_.K.call(this,"uv_r_frm");this.a=a};_.p(kq,_.K); var lq=function(a){_.K.call(this,"uv_r_rdm");this.a=a};_.p(lq,_.K);
var mq=function(a){var b=_.l.GTalkNotifier;return b?_.od(b):new _.kd(function(c,d){var e=_.Be(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Tf(a);f.addEventListener("load",function(){_.Ce(e);(b=_.l.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.Ce(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var nq=function(a){_.L.call(this);this.a=a.get(_.T);a=new _.N(this);_.I(a,a);a.listen(this.a.J(),"capi:r_clre",this.h);a.listen(this.a.J(),"capi:r_rrst",this.b);a.listen(this.a.J(),"capi:r_rers",this.g)};_.p(nq,_.L);nq.prototype.h=function(a){a=new Np(a.S);_.M(this,new oq(_.C(a,Pp,1)))};nq.prototype.g=function(){_.M(this,"I")};nq.prototype.b=function(){_.M(this,"H")};var oq=function(a){_.K.call(this,"G");this.a=a};_.p(oq,_.K);
var pq=function(a){_.N.call(this);this.b=a.get(_.Pf);this.a=a.get(hq);this.listen(this.a,"uv_r_rdm",this.Eb);this.listen(this.a,"uv_r_frm",this.Db);this.listen(this.b,"G",this.ic);this.listen(this.b,"H",this.Cb);this.listen(this.b,"I",this.Fb)};_.p(pq,_.N);_.g=pq.prototype;_.g.ic=function(a){a=(a=a.a)?[_.D(a)]:[void 0];this.a.reload(a)};_.g.Cb=function(){var a=this.a,b=new Sp;a.a.sendMessage(b)};_.g.Db=function(a){var b=this.b;a=!!a.a;var c=new Mp;_.B(c,1,!!a);b.a.sendMessage(c)}; _.g.Eb=function(a){if(a.a&&(a=a.a[0])){a=new Pp(a);var b=this.b,c=new Lp;_.E(c,1,a);b.a.sendMessage(c)}};_.g.Fb=function(){var a=this.a,b=new Rp;a.a.sendMessage(b)};
var qq=function(a){return new _.kd(function(b,c){_.Je(_.zf(a,"/webchat/extension-start"),function(a){_.Te(a.target)||c();try{var d=JSON.parse(_.Ue(a.target));b(new _.Rf(d))}catch(f){c(f.message)}})})};var rq=function(a){_.K.call(this,a[0]);this.S=a};_.p(rq,_.K);var tq=function(a,b){_.F.call(this);this.v=(0,_.sa)();var c={},d=$p(a,1,"hangouts.google.com"),e="";0>d.indexOf("://")&&(e="https://",0<=d.indexOf(":")&&23!=_.A(a,2)&&27!=_.A(a,2)&&(e="http://"));-1!=d.indexOf("talkgadget.")?(c.clientBaseUrl=e+d+"/talkgadget/_/",c.clientUrl="chat"):(c.clientBaseUrl=e+d+"/webchat/u/"+$p(a,8,"0")+"/",c.clientUrl="load");c.authUser=$p(a,8,"0");c.propertyName=_.Ff(_.A(a,2));c.locale=_.A(a,4);c.hideProfileCard=!0;c.parentToken=_.A(a,3);c.isRtl=$p(a,6,!1);c.lazy=$p(a,7,
!1);c.entityId=_.A(a,9);c.hostSettings=_.A(a,5);c.jsmode=_.A(a,11);c.isFullFrame=$p(a,13,!1);c.rosterId=$p(a,12,"talk_roster");c.rosterIframeIdB=$p(a,15,"gtn-roster-iframe-id-b");c.derp=!!$p(a,16,!1);d=_.C(a,Up,14);null!=d&&(c.isCentralRoster=$p(d,1,!1),c.useQuasarPanels=$p(d,2,!1));d=_.C(a,Xp,10);null!=d&&(c.moleManagerLeftMargin=_.A(d,1),c.moleManagerMiddleMargin=_.A(d,2),c.moleManagerRightMargin=_.A(d,3),c.moleManagerNoMoleAreaMargin=_.A(d,4),c.moleManagerBoundingElementId=_.A(d,5),c.moleWidth=
_.A(d,6),c.moleHeight=_.A(d,7),c.minimizedMoleHeight=_.A(d,8));d=_.C(a,Wp,18);null!=d&&(c.optOutAllowed=$p(d,1,!0),e=_.C(d,Vp,3),null!=e&&(c.legacyTalkSignedIn=$p(e,1,!0)),d=_.A(d,4),null!=d&&(c.useSpareMole=d));c.uiVersion=2;c.hideStatusMsgs=!0;c.hideRecentConversations=!0;d=new Ip;_.B(d,2,!0);_.B(d,1,!0);_.B(d,3,!1);c.endpointConfig=d;c.ignoreAutomatedRoster=$p(a,17,!1);c.conversationId=_.A(a,19);this.g=c;c=this.a=new Tp(this.g,!0,this.g.endpointConfig);var f=this.a.ma,d=this.a.b;if(-1!=f.indexOf("talkgadget.")){var e=
_.yf(f),h=e.a;if(0<=h.indexOf("/u/"))d=f;else{f=h.lastIndexOf("_/");if(0>f||f!=h.length-2)h+="_/";e.a="/u/"+d+h;d=e.toString()}}else d=f;c.ma=d;this.a.h=window.location.origin;this.b=null;this.l=new _.L;c=_.qb(this.g);c.endpointConfig=_.D(this.a.c);this.h=new b(c,!0);this.j=new _.ig;_.I(this,this.j);sq(this)};_.p(tq,_.F);tq.prototype.sendMessage=function(a){this.xa(_.D(a))};tq.prototype.xa=function(a){this.c("_h",a)};tq.prototype.$a=function(a){this.b=a;_.G(this,function(){this.b=null},this)};
tq.prototype.J=function(){return this.l};var sq=function(a){var b=eq(a.a.ma,a.a.a),b=new fq(a.a,b,a.v,window.document);_.I(a,b);gq(b,a.a.Vb,function(){},function(){return uq(a)})},uq=function(a){_.mg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.c("_addClientMessageCallback",function(b){a.b&&a.b.xa(b);_.M(a.l,new rq(b))});a.c("_rosterIframeLoaded")}; tq.prototype.c=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var vq=function(a){_.z(this,a,"h_ext",null)};_.p(vq,_.y);vq.messageId="h_ext";var xq=function(){_.N.call(this);_.S("Starting ...");this.a=new _.Jg;_.I(this,this.a);this.j=null;this.h=[];this.listen(window,"unload",this.Z);this.c=new _.Kf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.A(this.c,1),b=new _.ig;_.kg(b);b.a=new _.cg((0,_.r)(b.H,b),a);b.a.da("*",void 0,void 0);b.g.push(_.xa(_.H,b.a));this.b=b;_.Ng(this.a,iq,this.b);this.listen(this.b.J(),"uv_qm",this.l);wq(this)},yq;_.p(xq,_.N);
var zq=function(a,b){null==a.h?b():a.h.push(b)},wq=function(a){_.S("Initializing ...");Zp(bq([qq(_.A(a.c,2)).then(a.w,void 0,a),mq(a.c)]).then(function(b){_.ga();var c=b[window.Symbol.iterator];b=c?c.call(b):_.fa(b);var d=b.next().value;b=b.next().value;if(a.K)b=null;else{var c=new Yp,e=_.yf(_.A(a.c,2)),f=e.b;null!=e.g&&(f+=":"+e.g);_.B(c,1,f);_.B(c,2,27);_.B(c,13,!0);_.B(c,17,!0);d=_.A(d,1);_.B(c,3,d);d=_.A(a.c,4);_.B(c,11,d);d=_.A(a.c,3)||"en";_.B(c,4,d);d=new Up;_.B(d,2,!0);_.B(d,1,!0);_.E(c,14,
d);b=new tq(c,b)}return b}).then(function(b){if(!a.K){b.$a(a.b);a.b.$a(b);a.j=b;_.Ng(a.a,_.T,a.j);b=new jq(a.a);_.Ng(a.a,hq,b);_.Ng(a.a,_.Pf,new nq(a.a));new pq(a.a);for(a.b.sendMessage(new Qp);a.h.length;)a.h.shift()();a.h=null}}),function(a){_.S("Failed to start : %s.",a||"")})};xq.prototype.w=function(a){var b=this;return new _.kd(function(c,d){b.b.sendMessage(a);_.A(a,1)||d("Unauthenticated");c(a)})};
xq.prototype.l=function(a){a=new _.Gf(a.S);var b=new _.Wf;Op(b,_.A(a,1));"onSendHostMessage"==b.a&&zq(this,(0,_.r)(function(){var a=new vq,d=b.content().toString();_.B(a,1,d);this.j.sendMessage(a)},this))};_.wa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Eg();if(!_.m(yq)||null==yq||yq.K)yq=new xq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
